### ISSUE TITLE
Add compound phrases (`fuckbook`)

### ISSUE THREAD

**Issue by GusCaplan** [wooorm/alex#100]
The title

**Comment by wooorm** [comment]
...was quite long 😉

Sure, that’s possible. But it’s not a regex. Would you be interested in PRing?
The right places are [`profanities`](https://github.com/wooorm/profanities/blob/master/script/rest.txt) and [`cuss`](https://github.com/wooorm/cuss/blob/master/data/index.json).

**Comment by GusCaplan** [comment]
Sorry. I didn't write that cohesively. What i am proposing is a change to the way the input is parsed to find bad words that have been compounded. However, I just read the code, and this seems to span across three or four repos, so I may not get around to a pr. 😄

**Comment by wooorm** [comment]
No problem!

Yup, it won’t be easy to add total support for compounds, but I also think it would be very viable. think `rapist`, which is profane, but not in `therapist`. Now, I don’t believe the letters `fuck` are used in any non-profane words, but most are.

To keep false-positives low, I’d prefer just listing words in the aforementioned libs

**Comment by wooorm** [comment]
I added it to profanities; will add to cuss in a second. If you’d like to add more, please PR there!
