### ISSUE TITLE
UK is profane?

### ISSUE THREAD

**Issue by rugk** [wooorm/alex#102]
`I live in the UK.` shows:

> Be careful with UK, it’s profane in some cases

Why/when exactly is this profane? And I think even if there is some word I don't know, it is quite likely not written in capital letters as the United Kingdom.
So some case-sensitive checking would be useful here.

**Comment by wooorm** [comment]
Hi @rugk! Thanks for the issue! 🎉 Brexit related, maybe? 😉

I believe it’s a misspelt/shortened form of `uck` (you should be able to find definitions for that on [Urban Dictionary](http://www.urbandictionary.com)).

You pose two suggestions: the last being case-sensitivity. I don’t really like adding that, as that would make the algorithm quite brittle: it would be easy to get past the algorithm, and the algorithm would miss possible problems. I’d rather have more messages.

**alex** is not a very smart program. It emits many messages. It’s up to the human to handle those messages as they see fit. However, **alex** does already grade possible offences: `Be careful with UK, it’s profane in some cases`.

I suggest the section on [ignoring messages](https://github.com/wooorm/alex#ignoring-messages) in the readme.

**Comment by rugk** [comment]
Funnily even if I put the example `<!--alex ignore dad-mom-->` before the line Alex complains about, the warning goes away...
I think the correct one would be  `<!--alex ignore UK-->`, would not it?

The file method does not work, but I think this is an issue with the IDE integration I use: https://github.com/wooorm/atom-linter-alex/issues/17

**Comment by rugk** [comment]
Actually putting everything in a c omment before the line works:

```
	<!--fsdfds-->
	From: Devon, UK
```

**Comment by rugk** [comment]
I can reproduce this behaviour (without the indentation - which seems to affect Alex too) on http://alexjs.com/

Shows no warning:
```
<!-- ioo -->
From: Devon, UK
```

Shows warning:
```

From: Devon, UK
```

**Comment by wooorm** [comment]
@rugk That seems like a very different bug! Could you open another issue to discuss that?

**Comment by rugk** [comment]
Indeed. I'll do. :smile:
