### ISSUE TITLE
Suggestion: add the terms which include beg

### ISSUE THREAD

**Issue by dakshil** [wooorm/alex#104]
Tried the online version. Doesn't pick up the words containing beg.

**Comment by wooorm** [comment]
Hi @dakshil, thanks for helping!

Do you have any suggestions of what terms to add?

**Comment by wooorm** [comment]
Oh and if you’d like to help you contribute to [retext-equality](https://github.com/wooorm/retext-equality#contributing), or [profanitities](https://github.com/wooorm/profanities)/[cuss](https://github.com/wooorm/cuss)!

**Comment by wooorm** [comment]
@dakshil Ping!

**Comment by dakshil** [comment]
Ohh sorry. Am in the process of moving so got caught up.
http://www.thesaurus.com/browse/beg
Here are the replacement words for beg.

**Comment by wooorm** [comment]
:+1:

Could you also expand on why you think alex should highlight `beg`? Do you have sources which describe why it’s insensitive?

**Comment by dakshil** [comment]
https://en.m.wikipedia.org/wiki/Talk:Begging

http://www.dictionary.com/browse/begging

Please see synonyms part. The word beg has become demeaning or slightly
degrading. Telling someone to, stop begging you to do them a favour, for eg
comes across as them being needy.
The term isn't exactly friendly and alternative words are being used now a
days.

**Comment by wooorm** [comment]
@dakshil Hi 👋 

The by you linked article doesn’t explain what I asked for. It contains one comment by an anonymous user, which I don’t find a good source. In fact, from Googling around a bit I find more references to panhandling being bad.

Could you find a better source? Or get some community support for this?

**Comment by wooorm** [comment]
Thanks for raising, again, I’m closing this for the aforementioned reasons.

Don’t forget that you can always create your own retext plugins if you’re so inclined, and roll your own “alex”.
