### ISSUE TITLE
Bad Grammar

### ISSUE THREAD

**Issue by pocketbird** [wooorm/alex#11]
Using "theirs" to replace "his" doesn't work.  You're using a plural to refer to a singular subject.  Should be (at least) "his/hers" to replace "his."  

![image](https://cloud.githubusercontent.com/assets/1628599/9641961/264d57dc-517f-11e5-86c7-19541e4f783d.png)

It's not really offensive to use "his" *or* "hers" in a sentence when referring to a singular subject of unknown gender.  It's just proper grammar.  What *is* offensive is assuming that anyone using "his" or "hers" to refer to a subject of unknown gender is using it because he or she desires to be deliberately exclusive.  

All that said, if you're proposing we change the rules of the written English language or hoping to push "theirs" as an official word choice to refer to plural *and* singular subjects, then you're on the right track.  Although, the word "theirs" exists for the purpose of clarity because in a group you can have multiple genders while as a singular entity you can only have one.  

If you're arguing that someone can have *two* genders at the same time or none at all, then you need to make a decision whether someone who is dual-gendered receives a plural (making them 2 persons) and someone who is non-gendered receives... I don't know?  In this scenario, you might be best off inventing a word or two, as is common practice throughout history when a language needs a new word to define something.  

I think the vision for and purpose of alex is great, by the way.  I raised this issue because I desire to see this project reach its full potential but, I currently lack the time to submit a PR myself.

**Comment by wooorm** [comment]
Thanks for the issue. I’ll read this now but before I start: http://languagelog.ldc.upenn.edu/nll/?category_name=singular-they and http://english.stackexchange.com/questions/48/is-there-a-correct-gender-neutral-singular-pronoun-his-versus-her-versus/55#55!

**Comment by wooorm** [comment]
Okay: again, thanks for raising the issue. You provide some very philosophical points: introducing new words to the English lexicon and whatnot. Have you seen [xe](https://genderneutralpronoun.wordpress.com/tag/xe/)? Very interesting indeed. I don’t think I can persuade enough people by adding it here. Maybe [Sweden](https://www.washingtonpost.com/news/worldviews/wp/2015/04/01/sweden-is-about-to-add-a-gender-neutral-pronoun-to-its-official-dictionary/) can though.

Also, I acknowledge that (probably) most people do not intent to be offending when using `he`. However, I’m certain that some people reading it will find it offensive. And that’s where alex comes in. It’s not to make you feel guilty, it’s to be more inclusive towards the people reading your text.

If there’s no good alternative to your sentence. So be it, that’s the language and you’ll have to either resort to using funky phrasing like `xe`, make a choice to opt for a singular `their`, or just rewrite the complete sentence.

What do you wish alex would suggest?

**Comment by Charlotteis** [comment]
As someone who refers to themselves using gender neutral pronouns, people say "It is theirs" when talking about what I possess, rather than "It is hers". It works, I am happy with it.

Language is beautiful and adaptive. It can also be difficult to wield in all cases, but I think "theirs" is the right call here.

"his"/"hers" excludes everyone who is neither a "he" nor a "she".

There are many pronouns already used in the wild by people who do not feel that he/she fits. We shouldn't need to invent any more in the case of alex (unless, of course, you want to!)

Here is an awesome list of pronouns: http://my.pronoun.is/

:+1:

**Comment by wooorm** [comment]
@Charlotteis Thanks, and I agree :+1:

**Comment by pocketbird** [comment]
I think I understand - and I disagree but, regardless, I appreciate your thoughtfulness and reasoning. 

I haven't seen xe but, will check it out. 

Out of curiosity, @charlotteis you said "themselves" - do you consider yourself as having two separate identities or did you mean to say, "themself?" I think maybe "themself" is correct in this scenario, not "themselves." "Themself" being a new word but, not completely new, so to speak. It seems appropriate. 

This is the first time I've really considered this kind of thing to this extent so, please excuse my overly enthusiastic attention to detail haha.

**Comment by Charlotteis** [comment]
I don't think I used "themselves" in my comment. I would use "themself" personally. I consider myself to be a person, thats my identity :)

**Comment by wooorm** [comment]
I’m going to close this. Again, thanks for your question / opinion. I really appreciate it but I have to decline changing alex.

Anyway, feel free to re-open.
