### ISSUE TITLE
Add 'them' as option for him/her

### ISSUE THREAD

**Issue by NogsMPLS** [wooorm/alex#12]
Using demo site, example sentence:

"I like him." or "I like her."

Currently suggests:

"him may be insensitive, use their, theirs instead"

Would be better to suggest "them". Or at minimum, append "them" to the 'their, theirs' list.

**Comment by wooorm** [comment]
Will do. I’m adding some more profane words (everyone is typing horrible words in the demo and getting angry that they’re not highlighted) tonight, and I’ll add this too!

Thanks!

**Comment by todrobbins** [comment]
@wooorm++
