### ISSUE TITLE
Suggestion: add...

### ISSUE THREAD

**Issue by traustiasg** [wooorm/alex#126]
Suggestions of words that could be added

**eskimo** - may be insensitive
**half-breed -** may be insensitive
**half-caste**  - may be insensitive
**mick** - derogatory, racial slur
**negress** - derogatory, racial slur
**oriental** -  potentially offensive, commonly used term in the UK where it is not considered insensitive, it is considered offensive in the US however
**paddy** - derogatory, racial slur
**fruitcake** - may be offensive
**non-white**  - potentially offensive
**ghetto**  - potentially offensive
**africoon** - derogatory, racial slur
**beanbag** - derogatory, racial slur
**ching-chong** - derogatory, racial slur
**diaper-head** - derogatory, racial slur
**jewess** - derogatory, racial slur
**slanty** - potentially offensive
**spics** - plural for spic, racial slur

**Comment by wooorm** [comment]
Good ideas! Do you have some suggestions for alternatives?

**Comment by wooorm** [comment]
@traustiasg Ping!

**Comment by mathesond2** [comment]
Hi @wooorm! love the project, and figured I'd give this issue a quick jot..this is seriously offensive stuff to type out in an issue, but I suppose the point of Alex is to correct such language. :) Please let me know your thoughts, I'd love to contribute more.

**eskimo** - Inuit
**half-breed** - bi-racial
**half-caste** - bi-racial, multi-racial
**mick** - Irish person
**negress** - woman of African descent
**oriental** - Asian person
**paddy** - Irish person
**fruitcake** - gay man or lesbian woman
**non-white** - multi-cultural(?) <--not sure about this one
**ghetto** - urban(?) <--not sure about this one
**africoon** - person of African descent
**beanbag** - person of Mexican descent
**ching-chong** - person of Asian descent
**diaper-head** - person of Middle-Eastern descent
**jewess** - Jewish female
**slanty** - Asian person
**spics** - hispanics, latinos

**Comment by seanohue** [comment]
Perhaps "person of color" as a replacement for non-white
