### ISSUE TITLE
Detect the use `he/she` and `he or she`

### ISSUE THREAD

**Issue by leesdolphin** [wooorm/alex#127]
Currently typing `he` on it's own and `she` on it's own is detected by the `he-she` rule. However the use of `he/she`, `he or she` and the various other pronoun forms are not detected.

**Comment by leesdolphin** [comment]
So this change can be made really easily by changing line 30 in `index.js`

```diff
diff --git a/index.js b/index.js
index 128d7fa..e23a780 100644
--- a/index.js
+++ b/index.js
@@ -29,3 +29,3 @@ alex.markdown = alex;
 /* Processor. */
-var text = unified().use(english).use(equality).use(profanities);
+var text = unified().use(english).use(equality, {noBinary: true}).use(profanities);
```

However this simply creates 2 warnings; one for `he` and one for `she`. I'd prefer a more precise solution implemented in `retext-equality` to detect these as a candidate for replacement.

For example:

Input: ```He or she must own a computer```
Output: ``` `He or she` may be insensitive, use `they` instead```

**Comment by wooorm** [comment]
Indeed, it would be possible to add an option for that.

If you really need it now, I suggest going with unified directly (this is just a small wrapper around the by you highlighted code).

I’ll add support for passing `noBinary` in alex as well though.

Re the second part of your question: if you want to champion it, could you open an issue over on the correct repo ([retext-equality](https://github.com/wooorm/retext-equality))?
