### ISSUE TITLE
Why is "man" insensitive while "woman" isn't?

### ISSUE THREAD

**Issue by Ketchup901** [wooorm/alex#13]
https://i.imgur.com/2awDAA6.png

**Comment by wooorm** [comment]
Woops, sorry. That shouldn’t happen of course. The algorithm changed a lot while developing, that must’ve slipped through!

I’ll fix this later today!

**Comment by Ketchup901** [comment]
This is outrageous.
"Him" is a fucking PRONOUN. How is it insensitive? I feel very offended, it's as if I'm not a human being just because I am a man. This is what you call sexism.

**Comment by wooorm** [comment]
Again, sorry. I'll fix this later.

**Comment by Ketchup901** [comment]
This whole project is retarded and poorly coded. 
https://rbt.asia/g/thread/50073311

**Comment by Hual** [comment]
Hey, racial slurs aren't insensitive but 'man' sure is!

**Comment by SShrike** [comment]
@Hual, that's the biggest strawman I've seen all day.
