### ISSUE TITLE
Link in README to rules?

### ISSUE THREAD

**Issue by antislice** [wooorm/alex#134]
Hey, this is a really cool thing! I spent a good 10 minutes looking for the list of rules to figure out if this library would be the best fit for my use case, and finally found a link to [retext-equality](https://github.com/wooorm/retext-equality/tree/master/script) in an old issue. 

I'm not sure where you'd want it in the README or how you'd want the link phrased, but it would be really helpful!

**Comment by wooorm** [comment]
Also: wooorm/retext-profanities does the profane words (without suggestions)

**Comment by wooorm** [comment]
I added a paragraph covering this. Hope it helps?!

**Comment by antislice** [comment]
Yup, that definitely helps! Thanks for adding it.

**Comment by wooorm** [comment]
👌
