### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by RamonGebben** [wooorm/alex#14]
Are you planning or is there integration for multiple languages? 

If not what would be needed to accomplish this?

**Comment by wooorm** [comment]
Interesting. I’d love to. Latin-languages aren’t that hard. I use this parser for [English](https://github.com/wooorm/parse-english), which is pretty small, which is some code on top of [parse-latin](https://github.com/wooorm/parse-latin).

Then, there needs to be a pattern library. See the YAML files in [retext-equality](https://github.com/wooorm/retext-equality/tree/master/script) for more info.

What language are you thinking about? There might be unforeseen difficulties in some languages (I only speak Dutch and English, and a little german / french :smile:)

**Comment by RamonGebben** [comment]
Well I speak Dutch as wel but I work with an international team whom would
love to help out with with defining rules. So lets consider implementing
grammer files that the parser would work with this way anybody could submit
a new language.

Does that sound logical ?

**Comment by wooorm** [comment]
Yeah, have you seen the patterns in retext-equality? That's basically what's needed for other latin-script languages!
Again, love to help, and that sounds very logical. I think the best step now is to get started translating, if you'd like I can explain more about the types of patterns currently available. That might help get the 'mental framework' across needed for translating :)

**Comment by montogeek** [comment]
Please, add this, I want to make it available to Spanish language :)

**Comment by brunowego** [comment]
Portuguese language :+1:

**Comment by RamonGebben** [comment]
I created a glitter chat room to make communication go faster 
[glitter](https://gitter.im/RamonGebben/alex?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by wooorm** [comment]
@RamonGebben @montogeek @brunowego As noted earlier, this is possible, but we need patterns for each language. Would you be willing, and able, to contribute those?

**Comment by RamonGebben** [comment]
Sure, I think so if would you please explain a bit more whats needs to be done? I took a look at [this file](https://github.com/wooorm/parse-english/blob/master/parse-english.js) and it looks like we want some kind of better system to generate those regexes. Then we wouldn't need to write entire new patterns every time we want to add a language. What are you're thoughts on this?

**Comment by wooorm** [comment]
Are you talking about the [English abbreviation regexes](https://github.com/wooorm/parse-english/blob/master/index.js)? In that case, these are different per language, so the Dutch one also has a [custom expression](https://github.com/wooorm/parse-dutch/blob/master/index.js). There are probably lists on wikipedia for each language, so with one of those it would be a lot easier to add support for a language.

Also, most language have custom elision, such as the English `’n’` (e.g. in `Rock ’n’ Roll`), and the Dutch `’s` (e.g. in `’s Morgens`). So I need those kinds of exceptions too.

However, in theory, these are edge cases, and with just the patterns (see retext-equality), a lot can be accomplished too!

**Comment by RamonGebben** [comment]
Ow you already have a parser for Dutch. :) Then I can't help with developing other languages because only fluent in Dutch and English. :( How would one use Alex with Dutch?

**Comment by wooorm** [comment]
Pattern files, like the ones packaged with retext-equality need to be created first. Than I can think about how to support switching between these dictionaries: how they would be specified and such :)

**Comment by ryanberckmans** [comment]
I showed alexjs to somebody who avoids inconsiderate communication for a living. Her first question was "Does it support multiple languages?"

Our vote is for Spanish and French and we can contribute to those dictionaries.

+1

**Comment by wooorm** [comment]
Cool! :sunglasses: Regarding dictionaries, I can provide help with how the source code works (it’s all in [wooorm/retext-equality](https://github.com/wooorm/retext-equality/tree/master/script)). Other than that, some information regarding abbreviations in a language is needed for a [parser](https://github.com/wooorm/parse-english/blob/master/index.js) (plus also some edge cases where certain initial/final symbols and punctuation characters belong the their adjacent words, e.g., English has `2 o’ clock`, and Dutch has `’s Morgens`).

The most important is the translations themselves, which I’d be grateful if you could work on :smile:

**Comment by montogeek** [comment]
I can contribute to Spanish, but I dont know how exactly.

**Comment by wooorm** [comment]
Take a look at the link [above](https://github.com/wooorm/retext-equality/tree/master/script), those can be quite literally translated! Note that there’s of course a difference in languages: most translations shouldn’t be made literally, plus there might be new additions for other languages, and removals too!

**Comment by Far0s** [comment]
I will try to take a look this weekend at translating retext-equality in French :smile:

**Comment by wooorm** [comment]
Wow that’s so cool! :+1:

**Comment by montogeek** [comment]
I think I can work on it this weekend too

**Comment by wooorm** [comment]
Do ping me for help!

**Comment by SalomonSmeke** [comment]
I can help with Spanish. Natively bilingual Spanish + English. I'll look at the links above when I can :)

**Comment by wooorm** [comment]
@SalomonSmeke Cool! Ping me for help! 😄

**Comment by gsvolt** [comment]
Hey @wooorm, I was curious.. would it be cool to work on supporting languages like hindi? I know google translate handles hindi - but I really don't know your code base that well to know if any changes I make will work or not. I do know hindi and I'm pretty sure A LOT of Indians will appreciate alex.js I can read and write Arabic as well (but sadly cannot understand it) - with Arabic it'll have to take into account the right to left styles specific to that language I'd say.
Let me know what you think. I'm googling dictionaries online that provide data for hindi in the meantime.
@gsvolt

**Comment by SalomonSmeke** [comment]
I've been working on this in Spanish. And its tough. You did a great job in
English and its hard because many of those words aren't colloquially
equivalent to anything in Mexican Spanish. I'm even wondering if its
prudent to make "Spanish - mexico" variants.

**Comment by montogeek** [comment]
@SalomonSmeke What if we create an standart/neutral Spanish version?

**Comment by wooorm** [comment]
@gsvolt Wow, awesome. Great to hear. Please see my first comment above (https://github.com/wooorm/alex/issues/14#issuecomment-137497986) for more information. The fact that hindi isn’t Latin-script makes it a bit harder though.

**Comment by wooorm** [comment]
@SalomonSmeke @montogeek Cool. I’m not familiar with the differences between Mexican Spanish and Spanish, so I don’t thing I can correctly advise relating to the language. However, it seems like both could be useful, a “standard” Spanish version and a Mexican Spanish version.

Note that a Mexican Spanish plugin could itself “depend” on the “standard” Spanish plugin, so there’s no need to copy code, if you plan on building Mexican Spanish on top of Spanish.

**Comment by SalomonSmeke** [comment]
Well... Defining neutral Spanish is difficult. And if you do. There no
slang. And most of these terms are non existent. Which makes alex in
"neutral Spanish" less useful

**Comment by wooorm** [comment]
I don’t have time for this. If someone wants to pick it up I’d be glad to help, but I’m closing this as it won’t be included in the foreseeable future.

If you’re interested. Click “fork” on retext-equality, translate stuff, and publish!
