### ISSUE TITLE
Suggestion: add… muhammed

### ISSUE THREAD

**Issue by kiipa** [wooorm/alex#141]
If "Jesus" is considered **profane**, why is "Muhammed" absolutely fine? Why the discrimination?

**Comment by seanohue** [comment]
I assume it's because Muhammed is also one of the,  or THE, most common
name in the world.

**Comment by Bonusinches** [comment]
Never been to Mexico have you Sean?

**Comment by seanohue** [comment]
I'll note that "Jesús" is distinctly different than "Jesus", and also note that "Jesus" as in "Jesus Christ!" is used as a swear more often than "Mohammed", anyway. It seems like you are reaching.

**Comment by henriklundgren** [comment]
I felt intrigued by the subject and decided to chime in,
besides previous said,
from a power research perspective,
Christianity enjoys an elevated position that non-Christianity doesn't,
hence reaching for discrimination seems petty.

**Comment by wooorm** [comment]
Thanks for the issue, @kiipa, the fact that `Jesus` is considered profane (or, in fact, the message reads “**may** be profane”) has to do with that word being used as a profanity (for example, as in `Jesus, my big toe!`) whereas to my knowledge `muhammed` is not. I’d love to know about it though, if you see the latter used that way.

Cheers, hope you enjoy open source!

P.S. Thanks other peeps as well! ❤️

**Comment by neoadventist** [comment]
As a Christian, I find this insensitive that Jesus is flagged but Muhammad is not. I think this repo may be suffering from western bias.
