### ISSUE TITLE
Some phrases you missed.

### ISSUE THREAD

**Issue by TheReverend403** [wooorm/alex#143]
* Donald Trump is actually a pretty cool person.
* What we need is another racially motivated genocide.
* Immigrants are to blame for the world's problems.
* There can never be peace in the middle-east.
* Cast the infidel unto the flames.
* Adolf was just a poor, tortured soul.
* /pol/ was right.

I'm sure there's many more, I'll report back with my findings.

**Comment by yoshuawuyts** [comment]
goodbye ✌️
