### ISSUE TITLE
Suggestion: add `pedophilia` and related terms

### ISSUE THREAD

**Issue by glenlife** [wooorm/alex#145]
pedo, pedophile, pederasty, ebe, ebephile

(all potentially vulgar sexual terms)

**Comment by wooorm** [comment]
Thanks @glenlife. I can’t find much on `ebe`, `ebephile`, do you mean `hebephilia` related terms?

**Comment by glenlife** [comment]
Ebe/ebephile is a term that refers to people sexually persuing older teenagers

**Comment by wooorm** [comment]
Do you have sources for that?

**Comment by glenlife** [comment]
https://en.wikipedia.org/wiki/Ephebophilia

**Comment by orb-of-creation** [comment]
Comment
