### ISSUE TITLE
Resources for term additions related to disability

### ISSUE THREAD

**Issue by todrobbins** [wooorm/alex#15]
Here's a great overview of some of the disability related terms to parse:

* [An Introductory Guide to Disability Language and Empowerment](http://sudcc.syr.edu/LanguageGuide/)
* [National Center on Disability and Journalism Style Guide](http://ncdj.org/style-guide/)
* [Special Olympics Terminology Guide](http://www.specialolympics.org/uploadedFiles/Fact%20Sheet_Terminology%20Guide.pdf)

**Comment by wooorm** [comment]
Thanks a lot! I’ll try to implement this weekend.

**Comment by wooorm** [comment]
I just checked them again, they’re really great :)

**Comment by todrobbins** [comment]
Ha! Thanks. If I had a little more time on my hands I'd help make the additions. Cheers!
