### ISSUE TITLE
Feature request: Per-paragraph exclusions

### ISSUE THREAD

**Issue by pjf** [wooorm/alex#16]
I've just installed `alex`, and immediately ran it over the source of a book I've been co-authoring. It's fantastic, but I can't seem to spot a way to mark usages in certain paragraphs as being acceptable. For example, we have the line in our asciidoc source:

> . Click "Set GameData directory". A window will pop up; click "Set Data Dir"

Alex suggests "parent" as an alternative for "pop", even though "pop up window" isn't gendered. We can't use quotes here, as "*a window will "pop" up*" makes it sound like we're not really convinced that it's popping at all.

I'd *love* something similar to [perlcritic's ability to add directives in comments](https://metacpan.org/pod/Perl::Critic#BENDING-THE-RULES) to say that rules should be ignored in some cases. For formats which support comments, I'd suggest the following as a starting point, but of course you should adjust these as you see fit:

- `no alex` disables alex checking the next paragraph
- `no alex <wordlist>` disables alex checking only the words listed for the next paragraph
- `disable alex` disables alex checking until `enable alex` is seen (or end of file is reached, generating a warning)
- `disable alex wordlist` the same, with a wordlist
- `enable alex` re-enables alex checking (generates a warning if alex is already enabled)

If alex doesn't already have a concept of a paragraph, I'd suggest it to be the next sequence of one or more lines which do not consist entirely of whitespace. That preserves friendliness for comments which both contain embedded newlines in text, and those without.

Using the example above, we just want to ignore the warning for 'pop' for just one paragraph:

> // no alex pop
> . Click "Set GameData directory". A window will pop up; click "Set Data Dir"

This would mean for book-writing we can have alex as part of our continuous integration suite, and we can be sure that any language warnings can be either adjusted or approved by a human.

Many, many thanks again for a great tool!

~ Paul

**Comment by wooorm** [comment]
Would markdown comments, aka HTML comments work? So something like [this (the comment part)](https://github.com/wooorm/mdast-lint#configuring-mdast-lint)?

**Comment by sindresorhus** [comment]
> This would mean for book-writing we can have alex as part of our continuous integration suite

That's so cool! :)

**Comment by pjf** [comment]
> Would markdown comments, aka HTML comments work?

For markdown, yes please! :)

Asciidoc has its [own idea about comments](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments). Depending upon how you're doing parsing, I personally would be delighted if we saw any line starting with `// ` being checked for directives. (Asciidoc seems to be common at least at O'Reilly for book-writing, so there's an immediate use-case as part of the toolchain.)

Many, many thanks again!

**Comment by wooorm** [comment]
Yeah, forgot to say that it’s really awesome you’d like to include it!

There will be some difficulty in parsing asciidoc. Alex uses mdast to bridge markdown to natural language. It’s not just stripping markdown, there’s some difficulty in detecting `*in*sane` as a single word.
Similar technology needs to be added for proper asciidoc support.

Other than that, it would not be very hard to provide a new layer to replace markdown with some other format, but still, this is a huge step!
