### ISSUE TITLE
Suggestion: add delirious 

### ISSUE THREAD

**Issue by snood1205** [wooorm/alex#163]
Delirious is a word that is often used improperly like crazy.

**Comment by wooorm** [comment]
Good one, thanks for the suggestion @snood1205!

If you’d like to add `delirious` to alex, the right place to do so is a PR to add a new pattern in [`ablist.yml`](https://github.com/wooorm/retext-equality/blob/master/script/ablist.yml) in [`retext-equality`](https://github.com/wooorm/retext-equality).

Would you be interested in helping out?

**Comment by wooorm** [comment]
Oh and sorry for the late response!

**Comment by snood1205** [comment]
Certainly I can do that. No worries on the late response. Maintaining open source projects is a pain, so you're fine!

**Comment by wooorm** [comment]
Great! Let me know if you need help with anything!

P.S. That’s a very kind response, thank you!

**Comment by wooorm** [comment]
Fixed!

Thanks so much, @snood1205!

**Comment by snood1205** [comment]
No worries thanks for your help!
