### ISSUE TITLE
Translation: Spanish

### ISSUE THREAD

**Issue by agustingrigoriu** [wooorm/alex#165]
I think would be a good idea to translate it to Spanish

**Comment by fega** [comment]
I can help

**Comment by timrubio** [comment]
how do you want to help

On Thu, Apr 13, 2017 at 12:30 PM, Fabian Gutierrez <notifications@github.com

**Comment by fega** [comment]
I see Alex as a very interesting writing tool, I guess that will be great if it is translated or adopted in another languages

**Comment by agustingrigoriu** [comment]
I agree, I like the concept, It should be adopted not only in Spanish but other languages

**Comment by wooorm** [comment]
Hi folks! :wave:

We’ve discussed this a bit in GH-14 (and later GH-130). I’m all for multiple languages, but I can’t help with Spanish.

If you’re interested. Click “fork” on retext-equality, translate stuff, and publish! Afterwards, we can see how to integrate it into alex!

**Comment by timrubio** [comment]
lol

**Comment by BelenValdivia** [comment]
Hello! I want to participate too.

**Comment by wesamco** [comment]
I agree, all languages of the world should be added, it would be weird if in 2035 (before singularity hits) only the English speaking western world, or potentially every English speaking person in the world, spoke sensitively and the rest of the world didn't..

English speakers
Native: 360–400 million (2006)
second language speakers: 400 million;
as a foreign language, speakers: 600–700 million
total: 1500 milltion
source: [English Language - Wikipedia](https://en.wikipedia.org/wiki/English_language)
[List of languages by total number of speakers
](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers#Ethnologue_.282015.2C_18th_edition.29)

but objectively I doubt that future, where every person on earth🌍, would speak and write sensitively.. we would have to change their culture and traditions to be more secular, modern and western.. and that is a big challenge. 
I can help with the 5th most spoken language in the world, which is the language of the heavens (btw!),.. at least according to the most insensitive and intolerant books (which are written in that language),
and which books has the most drones.

but first we'll need new NLP POS taggers, the best ones I know of are stanford's, but they are written in Java, by a grad student with big models and data..

**Comment by codezplz** [comment]
I agree, all languages of the world should be added, it would be weird if in 2035 (before singularity hits) only the English speaking western world, or potentially every English speaking person in the world, spoke sensitively and the rest of the world didn't..

English speakers
Native: 360–400 million (2006)
second language speakers: 400 million;
as a foreign language, speakers: 600–700 million
total: 1500 milltion
source: [English Language - Wikipedia](https://en.wikipedia.org/wiki/English_language)
[List of languages by total number of speakers
](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers#Ethnologue_.282015.2C_18th_edition.29)

but objectively I doubt that future, where every person on earth🌍, would speak and write sensitively.. we would have to change their culture and traditions to be more secular, modern and western.. and that is a big challenge. 
I can help with the 5th most spoken language in the world, which is the language of the heavens (btw!),.. at least according to the most insensitive and intolerant books (which are written in that language),
and which books has the most drones.

but first we'll need new NLP POS taggers, the best ones I know of are stanford's, but they are written in Java, by a grad student with big models and data..

**Comment by wooorm** [comment]
Anyone interested in starting work on this?

**Comment by wooorm** [comment]
@agustingrigoriu Ping!

**Comment by agustingrigoriu** [comment]
I'm very sorry, i dissapeared because I started my thesis and also I began working. For the time being I can't find enough time to colaborate. I hope you can forgive me

**Comment by agustingrigoriu** [comment]
I talked to a friend and he is interested in taking my place in this task. Please explain him what to do to contribute. And again, sorry for dissapearing.

**Comment by ClaudioOliveda** [comment]
Hello, I want to take the place of Agustin.
Where are the files I should modify?
I await comments

**Comment by wooorm** [comment]
Sorry for the wait folks! Thanks @ClaudioOliveda for your interest!

The files that need to be translated are the YAML ones in [retext-equality](https://github.com/wooorm/retext-equality/tree/master/script).

For starters, I suggest the following workflow:

1. Fork `retext-equality`
2. Create a branch for Spanish
3. Translate the YAML files

...if those files are translated, we can see about making `retext-equality` support multiple languages. Maybe a [monorepo](https://lernajs.io)? Anyway, that’s stuff for later!

Does this help?

**Comment by wooorm** [comment]
Closing due to no response.
Feel free to ping again and I’ll re-open this issue if someone would like to work on this.
