### ISSUE TITLE
“browser” is marked as insensitive because of “bro” 

### ISSUE THREAD

**Issue by Haroenv** [wooorm/alex#166]
Possible solution: test if the rest of the word is “browser”, then don’t mark as insensitive.

Alex v4.0.1

**Comment by wooorm** [comment]
Could you provide more info? I’m not seeing `browser` being incorrectly highlighted.

**Comment by Haroenv** [comment]
Weird, I could definitely see it yesterday in my editor, but now it’s not marked as insensitive anymore. 

Thanks anyway!
