### ISSUE TITLE
Arabic Support / core multi-language extensibility model?

### ISSUE THREAD

**Issue by codezplz** [wooorm/alex#167]
I think it would be a good idea to add support for Arabic.
but first we would still have to work on secularism, separation of religion and state, tolerance or in general not taking religious texts too seriously. ☹

aside from the sad-but-it's-true-reality jokes, I'm serious about helping out. 
i'm a native Arabic speaker from.. the best place in the middle east you could possibly be in (OMG i'm so lucky for being born here, thank you god for that excellent choice, if you exist anyway..)

anyways..
we'll need new NLP POS taggers for each new language, the best one for Arabic I know of are Stanford's, but they are written in Java, couldn't find any in vanilla JS.

**Comment by wooorm** [comment]
That would be awesome! However, it does involve a lot of work.
I can help with that, but I can’t help with Arabic. Are you interested and able in taking this on?

**Comment by wooorm** [comment]
Sorry, didn’t mean to close it yet.

**Comment by wooorm** [comment]
@codezplz Ping!

**Comment by wooorm** [comment]
Closing due to no response.

Feel free to ping again and I’ll open it again if someone would like to work on this.
