### ISSUE TITLE
Ignoring messages does not work in versions later than 3.1.0

### ISSUE THREAD

**Issue by markcornick** [wooorm/alex#169]
None of the methods for [ignoring messages](https://github.com/wooorm/alex#ignoring-messages) work in `alex@latest`. Neither `.alexrc` nor `package.json` nor comments in Markdown are effective. The last known version supporting ignoring messages was alex 3.1.0.

[This gist](https://gist.github.com/markcornick/5d6588300c40c8936a8e9cc0544c368c) contains a script which will demonstrate this issue, and its output showing that `alex@latest` does not ignore messages by any documented means, while `alex@3.1.0` does ignore messages by all documented means.

**Comment by markcornick** [comment]
Observed on macOS Sierra (16.5.0) with the following `npm version`:

```son
{ npm: '4.2.0',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.9.0',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.43',
  zlib: '1.2.11' }
```

**Comment by wooorm** [comment]
Oh gosh, I haven‘t pushed alex@4.1.0 yet! 😱
I just did, I think it should work, could you check again?

**Comment by markcornick** [comment]
`alex@4.1.0` does work, with no issues found at any point of my test script. Thanks!

**Comment by wooorm** [comment]
Pfew, good!
Sorry about that, and thanks for reaching out! 🎉
