### ISSUE TITLE
Ignoring files should not cause error

### ISSUE THREAD

**Issue by fahad19** [wooorm/alex#170]
## Problem

I am trying to run `alex` on a directory of markdown files, and one of the files there is ignored. And alex throws an error.

## Expectation

I think it should just silently ignore the file, without exiting with an error failing the build.

## Reproduce

To reproduce:

* Have two files in root: `README.md` and `MAINTAINERS.md`
* In `.alexignore`, ignore `MAINTAINERS.md`
* Run `$ alex *.md`

And you will get an error.

**Comment by fahad19** [comment]
Travis-CI build output for reference: https://travis-ci.org/Travix-International/frint/builds/231453498#L1895

**Comment by fahad19** [comment]
if I modify `unified-engine/lib/finder.js:148` ([link](https://github.com/unifiedjs/unified-engine/blob/4ca617b880b022d08cd0356abb03f9c298e06ed6/lib/finder.js#L148
)) a bit, it works like I expect it to:

```js
if (ignored) {
  try {
    // file.fail('Cannot process specified file: it’s ignored');
  } catch (err) {}

  return one(null, []);
}
```

**Comment by wooorm** [comment]
Thanks for using alex, @fahad19, and hi!

This is intentional. Globs are expanded, and you’re saying like “get README.md and MAINTAINERS.md”, but then “don’t get MAINTAINERS.md”, and alex knows not what to do.

The simplest fix is probably to let alex find files itself: `alex .`
Could you check if that works?

**Comment by fahad19** [comment]
@wooorm: that worked! I will close this issue.

thanks for being so quick and helpful!

**Comment by wooorm** [comment]
Great!  Sure, no problem, and glad to hear!

👋

**Comment by tymonx** [comment]
I want to re-open this issue because it still causes some issues in some cases.

Related:
- https://github.com/get-alex/alex/issues/338
