### ISSUE TITLE
Suggestion: Add support for slang and word combinations.

### ISSUE THREAD

**Issue by linyostorovoltos** [wooorm/alex#174]
For example, the word "niggerfaggot"  is perfectly clear, while it is indeed highly offensive! I was pretty disappointed when I found things like the above example and things like "boipussy" and other offensive words that aren't in the dictionary aren't recognized as offensive. Another example is the word "smallcock" which returns with no issues found.

**Comment by wooorm** [comment]
This project is primarily intended for technical documentation, and these words are highly unlikely to appear there.

This project is not intended to be a spam filter: there’s many ways to get around alex if that’s your goal, leetspeek, etc.

If you’d like to add profanities to be checked by alex, the right place to do so is a PR to [`profanities`](https://github.com/wooorm/profanities).
