### ISSUE TITLE
`node_modules` is not ignored by default.

### ISSUE THREAD

**Issue by pierreneter** [wooorm/alex#175]
Alex version: `4.1.0`

`node_modules` is **not** ignored by default.
When I run `alex` It checks everything in `node_modules` path.
I tried adding `node_modules` to the `.alexignore` but it still causes errors that make the tests not pass:
```
"1:1 error Cannot process specified file: it's ignored"
```

**Comment by wooorm** [comment]
The word “default” here means if you’re using `alex`.

`node_modules` are also ignored if you’re passing in files and directories (`alex docs readme.md`).

`node_modules` are *not* ignored if you’re passing in globs that match files, as globs are often expanded by the shell: alex doesn’t see `**/*.md`, it gets for example `readme.md node_modules/something/readme.md`.

As a fix, use `alex .`, and then add patterns to `.alexignore` that you don’t want checked.

Also: maybe the [`--diff`](https://github.com/wooorm/alex#workflow) flag is of interest.

**Comment by pierreneter** [comment]
So about:

```
"1:1 error Cannot process specified file: it's ignored"
```

**Comment by pierreneter** [comment]
I have tried, and `quiet`  flag doesn't work with `.`?

**Comment by pierreneter** [comment]
I think I do not need to use the `--diff` flag for `travis-ci` now because the previous changes still need to be checked. After the process is complete, I will add it later.
So, thank you for the suggestion about this flag.

**Comment by wooorm** [comment]
Not?

```sh
🚀  example: alex
doc/getting-started.md: no issues found
doc/plugins.md: no issues found
readme.md: no issues found
🚀  example: alex -q
🚀  example: alex -q .
🚀  example: 
```

Could you provide information on how you’re running things?

**Comment by pierreneter** [comment]
Oops, sorry, my typo.

**Comment by pierreneter** [comment]
Thank you for explaining. 
I feel satisfied with the script:
```
alex -q .
```
