### ISSUE TITLE
Countries labeled as profane

### ISSUE THREAD

**Issue by suicidal** [wooorm/alex#178]
I recently ran a writing through your system about western / central Africa and I noticed that your system detected the country of "Niger" as a profane word, same for the term Africa.

**Comment by wooorm** [comment]
Hey!

Africa is already marked as an unlikely profanity, and I just did the same for Niger in the lower-level `cuss` module, as the words can still be used as a profanity. alex isn’t very smart, but it can help find things you may have forgotten. Anyway, you’re the human, you’re much smarter than alex.

Thanks for reporting!
