### ISSUE TITLE
An insensitive word sorrounded by commas is not detected

### ISSUE THREAD

**Issue by jeremenichelli** [wooorm/alex#179]
**Issue:** sensitive word is not detected when it has a comma before and after it.

**Version:** current version running in the demo site.

Here's an example, when the word has a comma after it, it gets detected.
![captura de pantalla 2018-02-08 a la s 23 09 41](https://user-images.githubusercontent.com/3856481/36001090-73a65240-0d25-11e8-8387-e10dc9794d4e.png)

Also when a comma is before it:
![captura de pantalla 2018-02-08 a la s 23 09 52](https://user-images.githubusercontent.com/3856481/36001114-877c376c-0d25-11e8-826d-b3cf9b8da2af.png)

But when both commas are present Alex ignores it:
![captura de pantalla 2018-02-08 a la s 23 10 01](https://user-images.githubusercontent.com/3856481/36001126-9478b148-0d25-11e8-944b-e0c922582cd7.png)

**Comment by wooorm** [comment]
This is a feature. These words, [literals](https://github.com/syntax-tree/nlcst-is-literal#usage), are ignored!
