### ISSUE TITLE
Feature request: .alexrc configuration

### ISSUE THREAD

**Issue by pjf** [wooorm/alex#18]
It would be wonderful to have a configuration file which is used by alex to modify its default behaviour. For example, we probably want to warn about gendered pronouns in technical writing, but not when writing a novel.

Drawing inspiration again from perlcritic, I'd suggest the following:

* A config file can be manually given on the command-line (eg: `--config=...`).
* If no command-line option was provided, alex checks in the current directory for an `.alexrc` file containing configuration.
* If that file is not found, alex checks the user's home directory for an `.alexrc` file.
* Only one configuration file is used.

This means that one can distribute an `.alexrc` file with a project (eg: checked into git) and it will be used when working on that project, and this will override the user's own settings in the default case. (This is really handy for group projects.)

Checking only two locations (cwd and home) means our behaviour is fast and well-defined. Making sure that only one config file is ever used means that collaborators can be sure they'll be using the same settings.

At the very least I'd see to see a config which means one can:

* Specify a list of words as 'acceptable', meaning they will not produce warnings
* Specify a list of words as 'unacceptable', meaning they will give warnings.
* Specify a list of safe command-line options that should be used. (I know that's none at the moment, but I'm sure it won't stay that way.)

Many thanks again!

~ Paul

**Comment by sindresorhus** [comment]
I think this is a good idea, but we should add "Check for an `alex` field in package.json" (see [`pkg-conf`](https://github.com/sindresorhus/pkg-conf)) as the second step. This is common for ESLint, XO, and many other tools, so not to add even more meta files to your project.

**Comment by wooorm** [comment]
Great idea, I agree that the current impossibility of configuring alex is a huge flaw. Nobody has the same standards! I’ll try to get the time to work on this next week :smile:

**Comment by wooorm** [comment]
Agree w/ @sindresorhus

**Comment by maxogden** [comment]
The best part of http://standardjs.com/ is that you can't configure it, which means it is easier to use. Not saying that completely applies here, but I like the fact that you can currently use alex with zero configuration.

**Comment by sindresorhus** [comment]
I would say the best part of something is not when you *can't configure it*, but rather when you *don't need to*. There will always be people needing to customize things. I think great defaults that works for most, but with configurability when needed, is the way to go.

**Comment by maxogden** [comment]
@sindresorhus well I disagree with you on `There will always be people needing to customize things`, but I agree with your overall point in this case. I mostly just wanted to voice my concern that feature creep + complexity are easy to add but hard to remove.

**Comment by wooorm** [comment]
@sindresorhus @maxogden I agree that non-configurability makes things a lot easier, but I do think this problem needs configuration. It’s just so loaded, and everyone has different standards.
Thanks for mentioning it though, feature creep is def. not what we want, duly noted!

**Comment by alexgleason** [comment]
Can it work the same way as spell check in Microsoft Word?

Your options are, when it finds a particular error, to "Ignore this instance" and "Ignore all".

Since many of these false positives are contextual, it makes sense to allow them on a case-by-case basis rather than allowing one word entirely then risk it being used badly in the future.

**Comment by liamdawson** [comment]
Another point of view here as well: I suggested it to one of my colleagues, they thought it was a bit too heavy-handed for their tastes. I think slowly working people onto Alex would be better than having them dismiss it out of hand, e.g. enabling Alex in a Slack room with fewer suggestions and gradually working up to the full set.
