### ISSUE TITLE
Penis is labeled as profane, but vagina is "maybe profane"

### ISSUE THREAD

**Issue by zakattak** [wooorm/alex#181]
Having a consistent label for the two genitals seems to be necessary.

**Comment by zakattak** [comment]
I just realized you're pulling this from retext - I'll open the issue there.

**Comment by zakattak** [comment]
Actually, after a small amount of digging, I'm not sure where the weight comes from for these two words. Let me know which repo I should create a new issue in.

**Comment by wooorm** [comment]
Hi @zakattak! It’s from cuss: https://github.com/words/cuss. You can open a PR / issue there. I’m not sure which weight to choose for either words though, but I guess syncing them makes sense.

**Comment by zakattak** [comment]
Yep, I think it's personal preference - I would say both of them are "maybe profane", because they are the anatomically correct words for genitalia. There are proper places to use those words. Again, it's my personal preference though, other people might not feel the same way.

**Comment by zakattak** [comment]
I've opened a PR there. Thanks!

**Comment by waldyrious** [comment]
> I've opened a PR there. Thanks!

Link for future reference: https://github.com/words/cuss/pull/14
