### ISSUE TITLE
What Hitler, Mao and Stalin have common with this Repo

### ISSUE THREAD

**Issue by ahmad2smile** [wooorm/alex#182]
Well, They all started with banning words. Any great civilization in human history it started with the Freedom of Speech and Freedom religion. Starting from Sumerians almost a 6000yrs ago. Successful civilizations started with religion and speech that led to great thinker and traders which in turn brought multiculturalism and all of those failed when they started to cling to specific religion or started controlling ppl's thoughts by speech.

One after another this has been happening for 6000yrs now. This happened in Roman Civilization, this happened in Christen Civilizations and even the same wheel turned in Islamic Civilization during Abbasians and Ummiyans and the same thing in current western civilization is going on. 

You guys have reached your peak as a culture and now whatever you are doing now is just a down hill journey. 

Why do I care? Because I don't see anything that can replace Western Civilization and when things gets bad in our countries, when we are facing Death here by Religious fanatics or in danger of getting politically murdered we run to Western Civilization. That's where we can run off too. 

But remember when when you guys mess up, give up your rights, cut the branch on which you are sitting on, there will be no space for you to run off too. This is gonna be it for you.

A society going feminized has never been tested but since its been happening in Western Civilization now things aren't looking any better.

Maybe you should think about whats the outcome you are getting by setting ppl's feelings as the decision factor. Trying to achieve absolution of anything just gonna make everything worse.

I never forget a line by one of our leader in Freedom struggle during British Rule over India,
something along the line as,

Civilizations in their decline cling to one thing and try to achieve its absolution.

**Comment by optikfluffel** [comment]
![WHAT?](https://user-images.githubusercontent.com/379915/36891684-b9be08c0-1e02-11e8-8e5f-2161c2e02a55.gif)

**Comment by seanohue** [comment]
so glad to contribute to a repo that will bring about the end of western civilization

**Comment by wooorm** [comment]
Aww, with a title like that I expected a joke about serial commas, but alas...

![comma-comma](https://user-images.githubusercontent.com/944406/36911574-3ddf04ec-1e44-11e8-978d-0d625d7ce03d.jpg)

> You guys have reached your peak as a culture and now whatever you are doing now is just a down hill journey.

We as a community prefer not to be addressed as “you guys”.

Finally, with regards to what I think you’re trying to tell us, @optikfluffel’s response is pretty apt:

> you do understand, that nobody forces anyone to use alex, right? If you don't like it, think it's unnecessary or even bad then please just move along and ignore it. Thanks.

...especially the lion king gif! 👍
