### ISSUE TITLE
"Boogey" isn't a word, and "boogie" is discriminatory

### ISSUE THREAD

**Issue by lschumm** [wooorm/alex#183]
The website uses "boogeyman" as an example of where the `-man` prefix can be deleted, removing the gender connotations of the word and maintaining the same meaning. However, the definition of "boogeyman" is (according to dictionary.com):

> an imaginary evil character of supernatural powers, especially a mythical hobgoblin supposed to carry off naughty children.

It suggests correcting to "boogey", which either is

> a lively form of rock 'n' roll, based on the blues.

or

> a contemptuous term used to refer to a black person.

In a context of referring to an individual as a "boogeyman", this could likely change a (gendered) term without any connotations into a confusing one with quite a few. Not a great example for the landing page...

**Comment by wooorm** [comment]
True! Could you do a PR to [change this line](https://github.com/retextjs/retext-equality/blob/df243a83774b109d9f35d26e4869355a7f9cc1b6/script/gender.yml#L557) with something else then?
