### ISSUE TITLE
Excessive scrollbars on demo

### ISSUE THREAD

**Issue by nornagon** [wooorm/alex#187]
Hi there! 👋 Thanks for working on this project! I think it's a fantastic tool :)

I noticed a minor issue on the website—on a Mac with a mouse plugged in, the demo messages are obscured by scrollbars:

<img width="567" alt="alex_-_catch_insensitive__inconsiderate_writing" src="https://user-images.githubusercontent.com/172800/40568346-f6cec024-602e-11e8-9972-26fb761af316.png">

**Comment by brenca** [comment]
I think it's not just mac.
![image](https://user-images.githubusercontent.com/1690458/40569468-234a228a-6082-11e8-9813-6bcf848a2be9.png)

**Comment by wooorm** [comment]
Done!
