### ISSUE TITLE
Pipe mode can't work

### ISSUE THREAD

**Issue by StarpTech** [wooorm/alex#189]
Hi, awesome work! I use it as a reference for the `unified-engine`. I noticed that

```sh
echo "test" | alex
```
or [here ](https://github.com/wooorm/alex/blob/master/cli.js#L59) can't work because the `files` option is always set and therefore the std stream is ignored. In my project I use a flag called `--stdin` to indentify the pipe mode and wheather he wants to redirect the output to a file or to stdout.

**Comment by wooorm** [comment]
Any suggestions on what we should do?

I’m thinking something along the following pseudo-code lines:

```js
if (input.length !== 0) {
  // use args
} else if (process.stdin.isTTY) {
  // definitely no stdin. use defaults
} else {
  someFunctionToReadFromStdin(function (_, buf) {
    if (buf) {
      // definitely stdin
    } else {
      // no data on stdin, use defaults.
    }
  })
}
```

/CC @sindresorhus - What do you think?

**Comment by sindresorhus** [comment]
Here's how I handle it: https://github.com/sindresorhus/strip-css-comments-cli/blob/ac32c3a959b3bc7cfc6c994b48c05b747bf9260b/cli.js#L34-L43

**Comment by wooorm** [comment]
Right, but we have [default globs](https://github.com/wooorm/alex/blob/d2fde314a5b1b0d441faaef53d8d73d87e28fa30/cli.js#L76-L81) if there’s no input 😬
