### ISSUE TITLE
Feature request: Why links

### ISSUE THREAD

**Issue by pjf** [wooorm/alex#19]
I see alex having great potential in helping people become aware of the meanings of words that they may have used habitually and without much thought. To assist this, I'd *love* to see a mode where not just warnings are provided, but also links to further resources as well. A pair of command line options (`--why` and `--no-why`) would be appreciated to enable or disable these links being shown.

Allowing links to be overriden on a per-word basis by a project's `.alexrc` file (#18) would also be fantastic. This means organisations using alex can link to their own style-guides, codes of conduct, or other resources as appropriate.

**Comment by wooorm** [comment]
The internal support for warnings has support for `ruleId` properties. Those could be used for links too.

It might be possible to add a link to each pattern. The same would go for author-provided patterns.

Overwriting is a bit harder though.

**Comment by wooorm** [comment]
How about the size of these things though? These sentences are already long: https://github.com/wooorm/alex/blob/master/screenshot.png

**Comment by pjf** [comment]
> How about the size of these things though?

That's why the suggestion comes with a command-line option to enable or disable the showing of links (and I'd suggest the default be disabled).

While probably overkill, perlcritic supports a whole range of verbosity levels for this sort of thing, with everything from tiny explanations, book references, to full on community-contributed explanations:

```
$ perlcritic --verbose=1 Quote.pm | head -1
Quote.pm:78:5:Expression form of "eval"

$ perlcritic --verbose=5 Quote.pm | head -1
Quote.pm: Expression form of "eval" at line 78, column 5.  See page 161 of PBP.  (Severity: 5)

$ perlcritic --verbose=10 Quote.pm
Expression form of "eval" at line 78, column 5.
  BuiltinFunctions::ProhibitStringyEval (Severity: 5)
    The string form of `eval' is recompiled every time it is executed,
    whereas the block form is only compiled once. Also, the string form
    doesn't give compile-time warnings.

        eval "print $foo";        # not ok
        eval {print $foo};        # ok
```

(The actual verbosity levels map to [format strings](https://metacpan.org/pod/distribution/Perl-Critic/bin/perlcritic#verbose-N-FORMAT) so you can also build your own.)

I'm not too worried about the length of the extra information, since I imagine the primary use for this is users wondering "why would X be problematic?" and running in `--why` mode to find out. (At least based upon all the times when I run perlcritic with `--verbose=10` to figure out why it objects to a particular line of code.)

**Comment by wooorm** [comment]
Okay. I’m afraid however that these description can become very long. There could be a whole blogpost attached, or a lot of links, to each warning. How to stop that? Is that wrong? Expected? What would you like to configure?

Could you give me an example of how you see an `.alexrc` file configuring a rule?

**Comment by wooorm** [comment]
As an alternative, mdast-lint uses [`ruleId`](https://github.com/wooorm/mdast-lint#command-line) properties for short, succinct, names. And It has [documentation for](https://github.com/wooorm/mdast-lint/blob/master/doc/rules.md#definition-spacing) each ruleId what it triggers for, sometimes also why, &c.:

Would it be a valid alternative to just have a link under the report with more information, and rule-names next to each warning?

**Comment by pjf** [comment]
> Okay. I’m afraid however that these description can become very long. There could be a whole blogpost attached, or a lot of links, to each warning. How to stop that? Is that wrong? Expected? What would you like to configure?

My envisioned user-experience looks something like this:

```
$ alex --why example.md

example.md
  239:123-239:129 warning `his` may be insensitive, use `their` or `theirs` instead (see: http://writingcenter.unc.edu/handouts/gender-sensitive-language/ )
```

That is, a single link presented to the user where they can learn more information. Not all warnings may have links, and if we allow users to customise their own rules then I'd hope they can customise their links as well (so they can point to project style guides or company policy). I presume that last part would preclude a link to the documentation for all the rule-ids.

As for the links themselves, we almost certainly want at least one level of indirection in configuration itself; lots of words deal with gendered language, and the chances are they can all link to the same place. (I'm not familiar with the internal workings of alex, but since you've mentioned rule-ids I presume we already have some grouping.)

Of course, this is very much a nice-to-have-but-not-essential feature. But given how often people are surprised at some of the [racial slurs](http://racerelations.about.com/od/diversitymatters/a/Five-Terms-You-Might-Not-Know-Are-Considered-Racist_2.htm) that have entered common language, I certainly love the idea of alex providing a ready means of education. :)

**Comment by wooorm** [comment]
Okay :) I have to say that this is a bit on the back burner for me though, but I agree that there should be access to some reasoning.

**Comment by ccoenen** [comment]
:+1: would be helpful, especially for non-native speakers.

**Comment by wooorm** [comment]
See the commit message for more info, new sources and notes can be added to retext-equality, similar to  [this](https://github.com/wooorm/retext-equality/blob/e564c4ae22d68920c201972054226038f2b953fe/script/ablist.yml#L12-L13).

**Comment by pjf** [comment]
You totally rock! Thank you! :)

**Comment by wooorm** [comment]
Thanks :) It’s not too beautiful right now though. I’d rather not implement a text-wrapping algorithm, however, maybe everything could be indented by two spaces or so? Or a line after the note?

![screen shot 2015-09-13 at 2 14 01 p m](https://cloud.githubusercontent.com/assets/944406/9836723/5b63f400-5a24-11e5-9a0e-cfa73e8e8131.png)
