### ISSUE TITLE
Consider adding w0rp/ale for vim to alexjs list of integrations

### ISSUE THREAD

**Issue by riley-martine** [wooorm/alex#191]
### Subject

On the "Integrations" section of alexjs.com, consider adding [ale](https://github.com/w0rp/ale), which will automatically use alex to lint files in vim.

**Comment by wooorm** [comment]
Sure, PR welcome!

**Comment by riley-martine** [comment]
I've sent two PRs (one for [readme](https://github.com/wooorm/alex/pull/193), one for [website](https://github.com/wooorm/alex/pull/192)).

**Comment by wooorm** [comment]
Thanks Riley!
