### ISSUE TITLE
Language standards are not consistant

### ISSUE THREAD

**Issue by moosehadley** [wooorm/alex#21]
Lines 19236 through 19245 establish that it is not okay to call someone "a bi-polar" or "a schizophrenic'
```javascript
    "type": "simple",
    "considerate": {
      "person with schizophrenia": "a",
      "person with bi-polar disorder": "a",
      "fluctuating": "a"
    },
    "inconsiderate": {
      "bi-polar": "a",
      "schizophrenic": "a",
      "schizo": "a"'
```
Yet lines 19144 through 19151 advise the user to call someone "a sociopath"
```javascript
    "type": "simple",
    "considerate": {
      "sociopaths": "a"
    },
    "inconsiderate": {
      "madmen": "male",
      "mad men": "male"
    },
```

**Comment by yoshuawuyts** [comment]
@moosehadley thanks for pointing that out, the feedback is appreciated. What do you suggest as an alternative to sociopath?

**Comment by wooorm** [comment]
Seems like quite the discussion: https://www.google.nl/search?rls=en&q=ableist+sociopathy
