### ISSUE TITLE
Consider including a list of psychological and psychiatric terms to avoid

### ISSUE THREAD

**Issue by evaryont** [wooorm/alex#22]
[See this article from Frontiers in Psychology](http://journal.frontiersin.org/article/10.3389/fpsyg.2015.01100/full).

Though I think this might not be directly related to the goal of unequal phrasing, instead "correct phrasing".

**Comment by yoshuawuyts** [comment]
PRs are welcome on https://github.com/wooorm/retext-equality! :grin:

**Comment by wooorm** [comment]
Thanks @evaryont!

**Comment by wooorm** [comment]
@evaryont Thanks for the list. I peered through it, but found no words relating to “insensitive” and “inconsiderate” words. They all seem to be relating to being deemed “inaccurate” in the psychological and psychiatric fields.

I may have missed some, but I don’t think alex is the place for these suggestions, therefore I decline this issue. If you do not agree and think some of these words should be added, please provide a more concise list of patterns which are `inconsiderate` and suggestions of `considerate` replacements.
