### ISSUE TITLE
Poor etymology leads to absurd censoring

### ISSUE THREAD

**Issue by nukeop** [wooorm/alex#23]
Examples:

"Mankind" ("manpower" etc.) is already a gender neutral word, it already encompasses all of what you suggest to call "humankind", same as "manslaughter" for example. http://www.etymonline.com/index.php?term=man

"Master plan", "master stroke" etc. is derived from adjective "master" which is not gender specific (a woman can have a master's degree for example).

"Freshman" (or "freshwoman", "frenchman", "showman" etc) are perfectly fine when referring to the person that is male or female, respectively.

"Mongoloid" is a word commonly used to refer to people native to some regions of Asia.

"Disabled"/"person with disabilities", "amputee"/"person with amputation", "handicapped"/person with physical handicaps" are for all intents and purposes functionally synonymous, and only introduce unneeded wordiness.

Master/slave when referring to servers, disks, and so on, have a completely different meaning and etymology than when referring to people. While the number of people living as slaves is at its highest point in history, it is doubtful that they care about computer science terminology. The terms "primary/replica" are rather confusing and frankly I have not seen them before anywhere other than this software.

And I don't think people who are mentally ill will appreciate the fact that you want to replace this description with "vile", "disgusting", or "mean".

In general I see this as a thinly veiled attempt at removing all traces of the concepts masculinity and/or femininity from the language that people use until it becomes ingrained in subconsciousness. There doesn't seem to be a purpose to this kind of censorship, unless you are addressing an unknown group of people.

**Comment by sindresorhus** [comment]
> "Mankind" ("manpower" etc.) is already a gender neutral word, it already encompasses all of what you suggest to call "humankind", same as "manslaughter" for example.

http://io9.com/5962243/think-twice-before-using-mankind-to-mean-all-humanity-say-scholars

> "Master plan", "master stroke" etc. is derived from adjective "master" which is not gender specific (a woman can have a master's degree for example).

Agreed, "master plan" by itself is ok.

> "Freshman" (or "freshwoman", "frenchman", "showman" etc) are perfectly fine when referring to the person that is male or female, respectively.

Agreed.

> Master/slave when referring to servers, disks, and so on, have a completely different meaning and etymology than when referring to people. While the number of people living as slaves is at its highest point in history, it is doubtful that they care about computer science terminology. The terms "primary/replica" are rather confusing and frankly I have not seen them before anywhere other than this software.

https://twitter.com/kwuchu/status/618799087006130176

> There doesn't seem to be a purpose to this kind of censorship, unless you are addressing an unknown group of people.

It's right in the tagline: "Catch insensitive, inconsiderate writing". This has nothing to do with censorship, and I'm surprised you see it as such. Alex is only meant to help us write more consderately.

**Comment by nukeop** [comment]
>https://twitter.com/kwuchu/status/618799087006130176

So, some guy on twitter said he "dunnos" how he feels about that, how is that relevant?

**Comment by yoshuawuyts** [comment]
@nukeop apparently he and at least 133 others don't feel comfortable using master / slave analogies. There are several alternatives available which `alex` will inform you of. It's always up to the author to decide whether or not to act on the information available.

**Comment by pjf** [comment]
> There are several alternatives available which alex will inform you of. It's always up to the author to decide whether or not to act on the information available.

Bingo. Alex is no different from a code linter or spell-checker. It can tell you that something *might* be a problem, but it's always up to the author to decide if it actually is.

**Comment by nukeop** [comment]
>@nukeop apparently he and at least 133 others don't feel comfortable using master / slave analogies. There are several alternatives available which alex will inform you of. It's always up to the author to decide whether or not to act on the information available.

>Bingo. Alex is no different from a code linter or spell-checker. It can tell you that something might be a problem, but it's always up to the author to decide if it actually is.

Well, I do feel comfortable with that terminology, and I come from a tribe that was enslaved so frequently throughout history that the word slave itself was derived from its name. I would like to remind everyone that slavery is not by any means limited to early USA and that white people such as Irish were slaves in USA in numbers as great or greater than blacks.

At any rate, this reminds me of a passage from a popular book:

 >The mind should develop a blind spot whenever a dangerous thought presented itself. The process should be automatic, instinctive. Crimestop, they called it in Newspeak.

>He set to work to exercise himself in crimestop. He presented himself with propositions—'the Party says the earth is flat', 'the party says that ice is heavier than water'—and trained himself in not seeing or not understanding the arguments that contradicted them.

**Comment by yoshuawuyts** [comment]
> Well, I do feel comfortable with that terminology,

It's not about you. It's about other people that do feel uncomfortable. See also discussions on why codes of conduct are required for conferences. If you feel your own opinion and feelings come before those of others, nobody will force you to change. Like I mentioned before: `alex` only exists to inform you of phrases that might be insensitive to others and suggest alternative phrasings.

Also regarding newspeak: this is not censorship. This is suggesting different words. If anything in time it will broaden vocabulary to include gender-, race- and religion-neutral terms in addition to the existing words and phrases.

Also fun fact: I'm the owner of the [`newspeak`](https://github.com/yoshuawuyts/newspeak) module on npm, I'm quite familiar with the terms haha.

**Comment by howardroark** [comment]
To be fair there is a slippery slope at play here.  The slack-bot listed in the README is sort of walking down the path towards censorship.  Who is to say that you don't wake up tomorrow to find a bot scanning all of GitHub and pointing out all of the people who are in violation of these conditions.  Maybe it ranks everyone with a score of how sensitive or insensitive they are and labels it along side their name and information. Then fear ensues and people start to act differently based from that fear... as opposed to from real genuine compassion.

I feel that there are some philosophical implications at play here.  It would not hurt to address them.

**Comment by nukeop** [comment]
"Compassion"? For what? You don't seriously think this kind of passive aggressive bullying towards self-censorship can be beneficial in any way, do you?

**Comment by wooorm** [comment]
@howardroark I respect your opinion but do not agree. alex was intended for people who’d like their own text to be sensitive and considerate towards others (IMO “self-censorship” is not a bad word).

Please, instead of commenting on every issue, open an issue to voice your concerns. But, only do so when I can act on it: the concerns you name are an infinite philosophical debate, probably better discussed over beer than on GitHub.
