### ISSUE TITLE
What does it detect?

### ISSUE THREAD

**Issue by gonmf** [wooorm/alex#24]
On the README it reads
> alex helps you find gender favouring, polarising, race related, religion inconsiderate, or other unequal phrasing.

but what exactly polarizing, race related, religion inconsiderate or other unequal phrasing is detected? I've tried some examples and nothing worked. Does it only detect a few pronouns and gendered nouns? Where can I find all the terms you chose as offensive? If it's someone elses list, who makes it? Why would I ever use this instead of just a simple ctrl+f?

**Comment by yoshuawuyts** [comment]
You can find the list of words used in https://github.com/wooorm/retext-equality. The list is updated based on community feedback, if you think it can be improved feel free to open issues / PRs about it! :grin:

> Why would I ever use this instead of just a simple ctrl+f?

`ctrl+f` responds to a query you created. `alex` returns results results you might not have been aware of prior to running it, by definition it would be nonsensical to use `ctrl+f` to search for an unknown query.

**Comment by gonmf** [comment]
Well then you don't address any of the things you claim then. All terms are gendered or master/slave vs primary/replica, which isn't racial unless you're trying to ignore all the reasons behind slavery that don't have to do with race.

>alex helps you find gender favouring, **polarising, race related, religion inconsiderate, or other unequal phrasing**.

is just false.

Also, as has already been point out, your suggestions are very simplistic and don't have anything to do with reality. for instance primary/replica cannot replace master/slave in many cases because the context is not of replicated mediums.

**Comment by yoshuawuyts** [comment]
Thanks for your criticism, it has been noted. Contributions to make `alex` better at detecting context would be much appreciated. Cheers!

**Comment by gonmf** [comment]
Just fix your false advertising.
