### ISSUE TITLE
Search all files in all folders of all types.

### ISSUE THREAD

**Issue by Charlotteis** [wooorm/alex#25]
I work on a lot of open source projects that have multiple folders, with multiple files. Documentation is not always in `docs`, and often they can take the form of .html files. I'd also like to be able to check code files (*.js, *.css) for bad code comments.

Is there a way to get Alex to check all directories and all file types within those directories in an easy manner?

Apologies if this is asking too much, I will try and work it out but I wanted to ask here in case there is an obvious way to achieve this.

**Comment by wooorm** [comment]
[This script](https://github.com/wooorm/alex/commit/c4480db5f52a8cc700e15a03c13a06cb9d57bf7a#diff-0730bb7c2e8f9ea2438b52e419dd86c9L161) might just be what you are looking for:

```sh		
$ alex $(git ls-files')
```

That lints all by Git known files!

**Comment by wooorm** [comment]
Also, with globbing, you could use something like `alex * **/*`, but that would include binary files (e.g., images), and hidden files. Maybe `alex $(find . -type f)` would be more suitable!

**Comment by wooorm** [comment]
IMHO this is not something which can be fixed in alex, rather, it’s something unix does well. Can I close this?

**Comment by Charlotteis** [comment]
I used `alex $(git ls-files)` and it took... some time :clock1: 
But, it does what I needed, so thank you! Feel free to close this :)

**Comment by wooorm** [comment]
On Pouchdb? I can indeed imagine that the size of that repo made it all a bit slower :)

**Comment by Charlotteis** [comment]
I'm finding that alex does not read everything when I do `git ls-files`. Not sure why that is, but I'm working on it! And yes, pouchdb slows things down :P

**Comment by wooorm** [comment]
Did you wrap with '$()'?
