### ISSUE TITLE
Display error & some ideas for more words

### ISSUE THREAD

**Issue by rugk** [wooorm/alex#26]
I think these screenshots should explain it quite good:
![alex01](https://cloud.githubusercontent.com/assets/11966684/9706650/6ff276c2-54ec-11e5-9d0d-d8ddcb4a15c1.PNG)

And:
![alex02](https://cloud.githubusercontent.com/assets/11966684/9706649/6fcf4706-54ec-11e5-9374-5cda35c85451.PNG)

**Comment by wooorm** [comment]
I opted not to introduce your suggestions. Thanks a lot, but they are “profane” words: there’s no argueing that they shouldn’t be used when you want to write “sensitive” and “considerate”.

**Comment by rugk** [comment]
Okay. I would just say that `cribble` is also profane IMO.

**Comment by wooorm** [comment]
@rugk These terms might be introduced after-all by GH-46!
