### ISSUE TITLE
Why is this named Alex?

### ISSUE THREAD

**Issue by rugk** [wooorm/alex#27]
I'm just curios: Is there some idea behind the name 'Alex'? I mean why is this soft5ware named like this?
Has the name a special meaning?

**Comment by wooorm** [comment]
It's a nice androgynous/unisex name, it was free on npm, and I like it :)

**Comment by sindresorhus** [comment]
@wooorm Maybe add it to a FAQ in the readme? I've gotten that question a couple of times too. Like: https://github.com/sindresorhus/ava#faq

**Comment by wooorm** [comment]
@sindresorhus Nice idea! Probably should also have a header something like “Why does this not have ‘X’, this is dumb” :wink:

**Comment by rugk** [comment]
:+1:  for a FAQ. :smiley:
