### ISSUE TITLE
Website display issue

### ISSUE THREAD

**Issue by rugk** [wooorm/alex#28]
I think already https://github.com/wooorm/alex/issues/26 displays it a bit, but here is a separate and more obvious issue for this.

![alexwebsitescrolling](https://cloud.githubusercontent.com/assets/11966684/9706717/c53baf7a-54ee-11e5-969e-8cc4b37c35ef.gif)

**Comment by wooorm** [comment]
Thanks for making the Gift, which browser are you using?

Basically there's a text area in front, and a div with similar styling behind it (with 'color' set to 'transparent', but with some spans with background colors).
However, having the styling in sync is pretty hard I found, so I'm not sure what it property is missing.

**Comment by rugk** [comment]
Nice that it's a gift for you - I thought it was only a gif. :wink: :laughing: 

Specs:
Firefox 40.0.3
Windows 7

**Comment by wooorm** [comment]
whoops, autocorrect ;)
Thanks for the info!

**Comment by jpruiz114** [comment]
Is there an example of how to use this on a website without node js? Just pure JavaScript and the library?

**Comment by danielhickman** [comment]
I was working on a `contenteditable` version of the input method. I ran into a few issues, but it can be done.

My progress is in my Alex extension, commented out.
