### ISSUE TITLE
Is there a pure JavaScript not node js implementation for web?

### ISSUE THREAD

**Issue by jpruiz114** [wooorm/alex#30]
I would like to know if there's a way to use this library in a website frontend with pure JavaScript.

Thanks,

**Comment by sindresorhus** [comment]
Yup, https://github.com/wooorm/alex/blob/master/alex.min.js

**Comment by jpruiz114** [comment]
This doesn't seem like a solution.

When you check the non minified version you see this dependencies:

/*
 * Dependencies.
 */

var bail = require('bail');
var mdast = require('mdast');
var bridge = require('mdast-util-to-nlcst');
var retext = require('retext');
var parser = require('retext-english');
var equality = require('retext-equality');
var sort = require('vfile-sort');
It also uses require.

Any posibility to provide a web browser example?

**Comment by jpruiz114** [comment]
This doesn't seem like a solution.

When you check the non minified version you see this dependencies:

/*
 * Dependencies.
 */

var bail = require('bail');
var mdast = require('mdast');
var bridge = require('mdast-util-to-nlcst');
var retext = require('retext');
var parser = require('retext-english');
var equality = require('retext-equality');
var sort = require('vfile-sort');
It also uses require.

Any posibility to provide a web browser example?

2015-09-07 22:38 GMT-05:00 Sindre Sorhus <notifications@github.com>:

> Yup, https://github.com/wooorm/alex/blob/master/alex.min.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wooorm/alex/issues/30#issuecomment-138421498>.
>



-- 
*Jean Paul Ruiz Vallejo*
Ingeniero Informático
m: (+57) 300-780-43-49
http://www.jeanpaulruizvallejo.com

**Comment by yoshuawuyts** [comment]
The output was bundled using `browserify -s` - https://github.com/wooorm/alex/blob/master/package.json#L80

The `require` statements are in there because of how browserify works; they can't be done away with.

In the browser do:
```html
<body>
  <script src="alex.min.js"></script>
</body>
```
And `alex` should be available globally. Cheers!

**Comment by wooorm** [comment]
@jpruiz114 you should try it out, it should work :)

**Comment by jpruiz114** [comment]
Hey there @wooorm @yoshuawuyts, I just gave it a try, not on browserify, with Chrome.

Tried it here:

http://www.jeanpaulruizvallejo.com/site/tests/js/alexjs-test-1.html

Got this:

Uncaught ReferenceError: alex is not defined(anonymous function) @ alexjs-test-1.html:13

I really want to use this library on a project of my own but not sure if the only way to use it is on a nodejs project and under browserify.

Any other ideas?

btw, thanks for taking the time to answer.

**Comment by wooorm** [comment]
Could you remove the `require.js` script?

**Comment by wooorm** [comment]
And just to make testing easier, swap out `alex.min.js` for `alex.js`

**Comment by jpruiz114** [comment]
Worked!!

Got it here:

http://www.jeanpaulruizvallejo.com/site/tests/js/alexjs-test-2.html

Thanks @wooorm.

If I may ask, what makes difference having and not having the "require" call?

And also, is different the minified version from the non minified one?

**Comment by wooorm** [comment]
require.js loads files from [the server](http://requirejs.org). If you later include alex it “thinks” it’s loaded by require.js. Thus, it doesn’t expose itself on `window`.
If there’s no `require.js`, alex does.

**Comment by wooorm** [comment]
An no, there’s no difference between `alex.js` and `alex.min.js`’s programming interfaces.

**Comment by jpruiz114** [comment]
Thanks for your time @wooorm and for the explanation. Again, great work here!!

**Comment by wooorm** [comment]
Thanks :smile:
