### ISSUE TITLE
Suggestion: would love to see this as a gulp task so you can check everything as you go

### ISSUE THREAD

**Issue by meetbryce** [wooorm/alex#31]

**Comment by yoshuawuyts** [comment]
It already exists - https://www.npmjs.com/package/gulp-alex

**Comment by meetbryce** [comment]
Awesome! thanks.

On Tue, Sep 8, 2015 at 1:35 PM Yoshua Wuyts <notifications@github.com>
wrote:

> Closed #31 <https://github.com/wooorm/alex/issues/31>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wooorm/alex/issues/31#event-403181641>.
>
-- 
Cheers,
Bryce York

**Comment by wooorm** [comment]
I'll add this to the integrations though
