### ISSUE TITLE
favors some polarizing universals over others

### ISSUE THREAD

**Issue by JacksonGariety** [wooorm/alex#37]
In its current form, Alex seems to primarily catch gender and race unipositivity. Thus, Alex is violating its primary goal goal: `catch insensitive, inconsiderate writing` by being inconsiderate of other struggles which may not be properly represented in the programming community.

Some examples of under-represented struggles: `class struggle`, `national struggle`, `species struggle`, `intra-species struggle` and also basic ones like `linguistic struggle` and `wavelength struggle` (colors only exist in relation to one another and so on).

For a specific instance: why should alex correct `her` and `him` to `their` but not `being` and `nothing` to `becoming`?

Within all universals can be found unbalanced polarity (see [Of Grammatology](https://en.wikipedia.org/wiki/Of_Grammatology)), so it would actually be more efficient to catch the words that *aren't* polarizing: `and`, `so`, `but` and such, as well as some proper nouns.

I'd be willing to start a fork if someone wanted to help.

**Comment by capitocapito** [comment]
Joking aside, I wonder if adding some sort of categories or tagging structure to the data might help. Users could instruct Alex to ignore or add specific lists related to their project.
