### ISSUE TITLE
'Banana' identified as 'Chinese person'/'Asian person'

### ISSUE THREAD

**Issue by john-adamson** [wooorm/alex#39]
In the online demo I typed `Banana Man is a superhero` and it highlighted `Banana` with the comment `Banana may be insensitive, use Chinese person, Asian person instead`.  I was expecting it to highlight `Man`...

**Comment by JacksonGariety** [comment]
well, bananas are yellow

**Comment by wooorm** [comment]
https://en.wikipedia.org/wiki/List_of_ethnic_slurs#b

**Comment by john-adamson** [comment]
Well, I can say I'm glad to be ignorant of that slur!

**Comment by wooorm** [comment]
😉 Not everything alex highlights can be used directly, however, they might make you think of looking for alternatives!
