### ISSUE TITLE
package description

### ISSUE THREAD

**Issue by JacksonGariety** [wooorm/alex#40]
I think this repo is tremendously interesting from a variety of points of view: psychological, semiotical, cybernetical, and philosophical! However, is it not less of a profanity checker and more of an inventory of ideological biases held or recognized by you, @wooorm?

An example: Alex "suggests" that `that's an illegal thing to do` might be changed to: `that's a Mexican thing to do`

I suggest (for the package description): `an experiment in the ideological biases of software engineering`.

EDIT: like all things, technology can be used for good or evil. The way it's presented, Alex is an insult to the poetics of life. I'm suggesting you recognize this in the GitHub page and the README.

**Comment by wooorm** [comment]
I don’t agree. Other people don’t either. In addition, I don’t hide that I am the original author behind some organization, Further, everyone is able to contribute. They have already done so.

Alex is _not_ an insult to “poetics of life”, just like spelling-control is not an insult to grammar.

**Comment by howardroark** [comment]
Would you concede that you are likely to be unaware of your own ideological bias?
