### ISSUE TITLE
he/she and it

### ISSUE THREAD

**Issue by neko** [wooorm/alex#42]
Pretty sure I'd find it more offensive if someone were to call me an "it" as opposed to a "he" or a "she".

**Comment by neko** [comment]
Some context:
![image](https://cloud.githubusercontent.com/assets/6992756/9875322/31257730-5bec-11e5-8921-922ca61245cc.png)

**Comment by wooorm** [comment]
I would say that “it” works well for Harry the Worm though?

In all seriousness, you are right. If you have another suggestion, please share.
Regarding that, `they` and `it` are merely suggestions. Most importantly, they work well
with technical writing as seen on GitHub, but not as much for fiction / stories.
Also: alex just highlights some points of interest. Authors should just see them that way,
alex does not enforce its rules.
