### ISSUE TITLE
Consider separating data into separate files or using a database.

### ISSUE THREAD

**Issue by alexgleason** [wooorm/alex#47]
alex.js contains so many lines of code it takes around 5 minutes to buffer in Atom text editor. It could be useful to separate the data into a directory of .json files, or consider switching to some form of database technology.

**Comment by wooorm** [comment]
That’s already in place, @alexgleason. `alex.js` is a compiled version of a lot of different Node modules, compiled using Browserify, for the browser. I recommend you browse `index.js` and `lib/**/*.js` files of all the different modules instead of trying to open the compiled file instead.

**Comment by alexgleason** [comment]
Thanks for clarifying!

**Comment by wooorm** [comment]
:+1:
