### ISSUE TITLE
Easily check source code through CLI

### ISSUE THREAD

**Issue by alexgleason** [wooorm/alex#49]
I'd like to scan a source code directory as plain-text files. I'd expect `alex **/*` or `alex -R .` to work but they don't.

**Comment by wooorm** [comment]
Yup, I’m all for this :+1:

**Comment by wooorm** [comment]
Thanks for the interest, @samhogg. I don't have much time, but I'm slowly working to this.

I'll first create vfile-find-down as a separate module, to search for files. That should provide a solid (tested) Base for this. Additionally, my just released vfile-find-down will provide the file-findjg system for configuration files.

Of you're really interested in working on a PR for Alex, I suggest the latter: use vfile-find-down (it's '.one' method) to find a '.alexrc' file with configuration (there's a separate issue for that, so if so, please respond there). Thanks for the interest!

**Comment by yoshuawuyts** [comment]
This could be useful for https://github.com/nodejs/diversity/issues/9

**Comment by samhogg** [comment]
Oh right, that's an interesting approach, I didn't think of the config side - although I would've thought that would just be using existing approaches to find the config file. I was thinking of using something like [`node-glob`](https://github.com/isaacs/node-glob) to handle patterns similar to the patterns @alexgleason gave examples of.

**Comment by wooorm** [comment]
@samhogg I did this (searching for configuration files upwards) with **mdast**, modelled after eslint. That ensures working in subdirectories still works as planned. And, additionally, cascading configuration files are possible (which is very cool :wink:).

node-glob, and globbing in general, is certainly useful. But you additionally need to search for files by extension for those globs to result in applicable files, something else is needed for that (vfile-find-down, that is).

**Comment by wooorm** [comment]
@yoshuawuyts Certainly!

I just came up with a possible alternative to use alex in CIs: just passing through additions.
That way, when alex highlights (causing the CI to fail) stuff but humans smarter than alex decide it’s to sensitive and still merge it in, next checks don’t cause those phrases to turn up again!?

Viable idea? Thoughts?

**Comment by jden** [comment]
The diff-only approach sounds good to me.

Human language can be tricky. To me the value in alex is not 100% adherence (as it might be with things like code style linters), but in providing another layer of sensitivity checking. And because the feedback is automatic and coming from a tool rather than a person, it removes the element of ego, defensiveness and debate that sometimes is involved when insensitive language is pointed out through other means.

I'll also voice support for node-glob. It's cross-platform and works on Windows (without relying on the shell to expand glob patterns), which is used by a large number of node users (some 40% of visitors to npm.com have Windows useragent strings).

**Comment by wooorm** [comment]
@jden :+1: About the globbing: not to fret, I’m sure that’ll be included (in fact, there’s already globbing in place, even for Windows).

About the diffing CI: We probably need a separate module which, when run on Travis and the like, passes the diffs through alex. I have no idea how that could be accomplished, or if similar things already exist. Anyone ideas?

**Comment by samhogg** [comment]
> But you additionally need to search for files by extension for those globs to result in applicable files, something else is needed for that (vfile-find-down, that is).

Globbing works with extensions fine as far as I can tell? Or is there I am something I'm missing completely?

:+1: on the diffing idea, that's pretty smart. Would the approach be just checking additions relative to the last commit, or another branch?

**Comment by wooorm** [comment]
@samhogg What you’re missing is, when someone uses `alex docs/`, the `.md` and `.txt` files must be passed to alex, not `.html` or `.png` files!

Re the diffing: I’m not sure, ideally, if someone PRs a branch (with several commits) onto `master`, all those commits must be checked. I’m not sure if it’s possible to just detect what has changed (on travis?) though :/

**Comment by samhogg** [comment]
@wooorm with globbing I can do something like `alex docs/**/*.(md|txt)` which would do exactly what you want, and is a pretty common approach amongst node tools that I've seen.

In Travis/CircleCI you can access the git log, I guess it's whether you want it to be incremental on a commit by commit basis or diffing the entire branch (which could get messy)

**Comment by jden** [comment]
A naive approach is just to pipe the git diff through alex. the following could be added to a .travis.yml:

    git diff -U0 HEAD^ | grep -ve '^-' | alex

this suppresses unchanged lines, filters out deletions, and pipes it to alex

**Comment by wooorm** [comment]
@samhogg Certainly, it’s a start. But it doesn’t enable the second code example given by @alexgleason (on which I find very important).

@jden Nice, but we still need some parsing right (it might be my diff formatting but on my set-up that still includes funky lines). I had some luck with `git diff -U0 HEAD^ | awk '/^\+[^\+]/' | sed -r 's/^.//g'`, which reject lines not starting with `+`, and spits out all added lines without those `+`es. I guess parsing diff’s could certainly be done on travis in JS. The hard part is getting correct line and column numbers.

More in GH-58.
