### ISSUE TITLE
Suggestion: add…

### ISSUE THREAD

**Issue by suisea** [wooorm/alex#51]
stupid
mute
idiot

**Comment by yoshuawuyts** [comment]
Could you add some context to your suggestions? Thanks.

**Comment by suisea** [comment]
here you go! http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

sorry, i think i meant dumb instead of mute. and "*d*ot" has a medical etymology and as a result, used pejoratively, is a slur.

**Comment by wooorm** [comment]
Thanks @suisea, but these were added in wooorm/retext-equality@b5fd7bf019a4eb4a3f0120038d759bf0d95779b6, which was included in e5507626fa47427515758dfd7af0dd7f985749e5!

**Comment by suisea** [comment]
oh okay, for some reason they didn't show up on the alexjs.com site! @wooorm

**Comment by wooorm** [comment]
Done in 3527fb81e261ac601d352a2e99fc175aa60941c2!
