### ISSUE TITLE
Include "errors"

### ISSUE THREAD

**Issue by alexgleason** [wooorm/alex#52]
Just an idea I wanted to throw out there. Many of these phrases can cause false positive #33, such as "hosts", or the context in which the word is used matters.

I like that the phrasing is "xxx **may be** insensitive", because that accounts for this. And it makes sense for these words or phrases to return warnings.

However, some words are always insensitive just due to the nature of the word itself. I'm thinking of things like racial slurs and other derogatory terms. It might make sense for alex to output an error in red when it finds these words.

Obviously there would be challenges in doing this and I don't personally view it as high priority. Just wanted to share.

**Comment by wooorm** [comment]
Thanks for the idea @alexgleason, I agree.

I’m pretty sure all derogatory terms for [people of colour](https://github.com/wooorm/retext-equality/blob/42bf0555242316552cf4171c962af6014b451781/script/racial.yml#L414-L477) should all be called as what they are: an error.

However, not every pattern is that binary, e.g., [`armo`](https://github.com/wooorm/retext-equality/blob/42bf0555242316552cf4171c962af6014b451781/script/racial.yml#L6) might be used for both [people from Armenian descent](http://www.urbandictionary.com/define.php?term=armo) or a [lot of other things](https://www.google.com/search?q=armo).

How to handle those cases? I’d rather not go for a whole list of `might be`, `probably is`, `possibly is`, `quite likely is`, &c.

**Comment by liamdawson** [comment]
What about a confidence factor? That allows for different tolerances, and still a spectrum of outputs.

For example, a slur could give a confidence factor of 1, but disabled could be a bit less due to uses where it's a valid term (e.g. this setting is disabled by default). Then, in CI for example, you could choose a confidence factor for different things (minimum confidence 0.5 for README, 0.8 for code).

**Comment by wooorm** [comment]
Although not directly applicable. The just released [`2.0.0`](https://github.com/wooorm/alex/releases/tag/2.0.0) version of **alex** splits profanities from inclusivity warnings. The first are now more clearly mentioned as being vulgar. In addition GH-72 which will land in `3.0.0` will make the descriptions of messages more clear.

With both those, I feel this issue can be closed. If not, I’m fine with re-opening!
