### ISSUE TITLE
CLI only shows that there are warnings but not the reasons

### ISSUE THREAD

**Issue by mxlje** [wooorm/alex#53]
I feel like I’m missing something very obvious here. I installed alex globally through npm (as instructed) and I can run it normally, so there is no error message.

When I give it a file that contains offenses it only says that it found warnings, but not what the actual problem is. Example:

The file `test.md` contains the example string from the README:

```
The boogeyman wrote all changes to the **master server**. Thus, the slaves
were read-only copies of master. But not to worry, he was a cripple.
```

![mmtest zsh 2015-10-16 18-53-08](https://cloud.githubusercontent.com/assets/1345545/10555019/268844e8-7437-11e5-8135-51b77e757ba3.png)

Any ideas?

**Comment by wooorm** [comment]
Thanks for reporting. Sorry about that! That should’ve been fixed [now](https://github.com/wooorm/vfile-reporter/issues/2). Could you check again by uninstalling and re-installing alex?

**Comment by mxlje** [comment]
Thanks a lot, it works now 🎉

**Comment by wooorm** [comment]
Great! Thanks!
