### ISSUE TITLE
Katsap is what Ukranians call Russians, not the other way around

### ISSUE THREAD

**Issue by suchow** [wooorm/alex#54]
http://www.urbandictionary.com/define.php?term=Katsap

**Comment by yoshuawuyts** [comment]
PRs are welcome (':

**Comment by wooorm** [comment]
Thanks a lot @suchow!

**Comment by wooorm** [comment]
Thanks a lot @suchow!

**Comment by wooorm** [comment]
Sorry, thick fingers and small GH buttons :(

Could you create a PR?

Also: must've been a mistake by me when including the list of ethnic slurs from Wikipedia: https://en.m.wikipedia.org/wiki/List_of_ethnic_slurs

**Comment by suchow** [comment]
How do you want this fixed? A new rule added, existing ones amended?

**Comment by wooorm** [comment]
Thanks for the interest! I prefer an amended rule :+1:

**Comment by suchow** [comment]
I don't see any rules that detect ethnic slurs against Russians, so I'm not sure how to do this via amendment other than to delete "katsap", but that seems less than ideal.

By the way, I'm a co-creator of `proselint` (http://proselint.com, w/ @michaelpacer & @laraross), an in-the-works linter for prose, and we have quite complementary goals in our projects. We should talk!
