### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by wooorm** [wooorm/alex#58]
Related: nodejs/inclusivity#9.
Related: GH-49.

This builds on thoughts previously posted elsewhere, for example:

> I never intended alex to be used in CIs. It highlights a lot (by design), and humans smarter than it should choose whether its too sensitive or whether it highlights valid points.
>
> However, I like the diff-only approach [...], that might actually work. For example, in the below flow:
>
> * A CI would pass the additions of a PR through alex;
> * alex finds stuff in the additions, and fails that CI task;
> * A member [...] checks it out and merges it anyway (because alex is overly sensitive) or halts the PR.
>
> The good part about this is that this flow has some part automation (removing human ego), and some part human (removing dumb automation).

(source: https://github.com/nodejs/inclusivity/issues/9#issuecomment-155759123)

I like this approach, the fact that a computer can fail a test, but a human can still merge it fits really well with alex.

I’m proposing a new module used specifically with CIs to test only additions.

Some random musings:

* [`TRAVIS_COMMIT_RANGE`](http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) seems to hold what we’re looking for

* Name: `alex-ci`, or is that misleading? Maybe `alex-travis`, but that might be to limited for future features (e.g., running locally before pushing).

* We need some way to detect which lines were added in which files in order to get the correct line/column for each warning.

**Comment by jden** [comment]
proposed name `alex-diff`

**Comment by sils1297** [comment]
We already have a bear for using alex in coala: https://github.com/coala-analyzer/coala/commit/c8239cddd1eee01fdb2b7ee2c7e67c4b914baa5d , with that you can use alex for GitHub pull requests via gitmate.com . (After that gets merged.) Because running servers cost money we'll make this service free for open source and paid for closed source.

**Comment by HugoGiraudel** [comment]
I am very interested to set up Alex.js as part of CI integration on Sass Guidelines. Is there any progress or workaround on this? 

Also, is there support for other languages than English so far?

**Comment by wooorm** [comment]
@HugoGiraudel This issue is still a concept. I’m not yet going to work on it. Partially because it means an Heroku subscription, and that costs money.

You mention “using alex in a CI”, that’s possible, e.g., by running `$ alex` somewhere in Travis or another CI. This issue is about PRs and the added/updated lines, which isn’t possible (on its own) yet.

Coala, mentioned above, could maybe help you here though, it offers a diff-based implementation of alex, I think.

**Comment by sils1297** [comment]
@HugoGiraudel yes, take a look at gitmate.io or app.gitmate.io , that's a prototype service that'll be able to run alex over documents you specify using coala. (At the same time it also can do other static code analysis on your code.)

**Comment by wooorm** [comment]
Closing for now as I’m not interesting in doing it now, nor do I have the time. I’d love it if someone made this into dedicated reality though! (but do check out alex-bear as mentioned above for now!)

**Comment by wooorm** [comment]
Reopening. I’ve got some ideas for this!
