### ISSUE TITLE
Find files outside of working directory

### ISSUE THREAD

**Issue by c089** [wooorm/alex#60]
Thank you for this helpful tool :heart_eyes_cat: 

It fails to check files specified using the CLI though, while reading from STDIN works as expected:

```
bash-3.2$ echo 'Our developers are great guys.' > /tmp/alex.txt
bash-3.2$ alex /tmp/alex.txt

bash-3.2$ cat /tmp/alex.txt | alex

<stdin>
  1:26-1:30  warning  `guys` may be insensitive, use `people`, `persons`, `folks` instead

⚠ 1 warning
bash-3.2$ node -v
v5.1.0
bash-3.2$ alex --version
1.6.0

**Comment by wooorm** [comment]
Thanks for reporting, @c089!

**Comment by c089** [comment]
Thanks, that was fast :) Not sure this is my bug though, because it also fails from the same cwd, i.e. `cd /tmp && alex ./alex.txt`.

**Comment by c089** [comment]
...but 1.6.1 fixed both :) Thanks a lot.

**Comment by wooorm** [comment]
Hmm, well, weird. Glad it’s fixed though :smile:
