### ISSUE TITLE
Add-on for Brackets by Adobe

### ISSUE THREAD

**Issue by ethanostrow** [wooorm/alex#66]
Hey, I know many people use Brackets as a text editor, is there alex for that? If not, that would be great!

[Brackets](http://brackets.io)

**Comment by wooorm** [comment]
@ethanostrow Thanks for the suggestion.

There’s no such plug-in yet, would you be capable and interested in creating it?

**Comment by wooorm** [comment]
I don’t have time for this. If someone wants to pick it up I’d be glad to help, but I’m closing this as it won’t be included in the foreseeable future.
