### ISSUE TITLE
Atom: Option to correct by clicking on suggested correct word

### ISSUE THREAD

**Issue by netsi1964** [wooorm/alex#67]
Great extension, tried it in Atom. I suggest that you add option to click suggested correct words and then have the marked words replaced.

**Comment by wooorm** [comment]
Thanks for the issue, @netsi1964.

First of all, please post plug-in related questions on the [atom-linter-alex](https://github.com/wooorm/atom-linter-alex) repo, in the future.

On to your question: out of my control, atom-linter-alex is built on the [AtomLinter](https://github.com/atom-community/linter), which provides the interface between messages and Atom. I suggest raising the issue over there, if you’d like AtomLinter to provide an interface for clickable suggestions which change the marked words into suggestions.

**Comment by netsi1964** [comment]
Sorry I posted to the wrong place, and thanks for your suggestion :-)

**Comment by wooorm** [comment]
:+1:
