### ISSUE TITLE
Provide orignal separate files instead of combined one

### ISSUE THREAD

**Issue by DrummerHead** [wooorm/alex#68]
Browserify is being used to combine several source files into `alex.js`, why not provide these source files along the bundle? It would make contributions and code analysis much easier. Cheers.

**Comment by wooorm** [comment]
If you use bower, you’ll get precompiled distribution files. I’ll remove bower support soon, and move the distribution files over to GH releases.

All other packagers receive the source files. Check out `index.js`.
