### ISSUE TITLE
Add support for Restructured Text

### ISSUE THREAD

**Issue by leesdolphin** [wooorm/alex#69]
Given that lots of documentation is written in Restructured Text(ReST), it would be good if Alex supported this 'natively'.

Code blocks in ReST are already indented, and inline code is wrapped in '\`'s. However other parts of ReST are also enclosed in '`'s, such as links which should also be linted.

**Comment by wooorm** [comment]
Would be cool, but there’s *a lot* of work involved in that: you need a powerful parser, which can take a while to create. As an example, the markdown parser took me ± two years to write.

If anyone is interested, be my guest, but I don’t see this happening (in the coming years), so I’m closing this.

P.S. have you used `alex.text()`, in JS, or `alex --text` on the CLI? It will lint the code in ReST too, but at least it’ll catch warnings in links and whatnot.
