### ISSUE TITLE
Project Rename

### ISSUE THREAD

**Issue by CodeForAllkind** [wooorm/alex#70]
The word alex is inappropriate.

I have an extensive knowledge of Greek history and linguistics - and can confidently say that the word "alex" is inappropriate for such a project.

Your project strives for equal rights, fair writing - why is your name the literal definition of defending men?
You should be PROMOTING equalism, NOT choosing a term like alex.

I hope you put my request under consideration - it would be a significant and symbolic step in rights for all. 

Sources for you to check up on:
http://www.behindthename.com/name/alexander
https://en.wikipedia.org/wiki/Alexandra

**Comment by lightdozer** [comment]
You are ridiculously, insanely stupid. I don't have anything other than that to say. Please never post anything publicly to the internet ever again.

**Comment by NightDevel** [comment]
I apologize if I have offended you.  Please understand where I am coming from - the world has its issues and I just want to help.

**Comment by CodeForAllkind** [comment]
You're mean.

**Comment by lightdozer** [comment]
Have you considered crying about how the completely nondescript name Alex is actually an offensive slur meant to denigrate you personally?

**Comment by CodeForAllkind** [comment]
Oh please.

**Comment by GreenTurtleOne** [comment]
I'm sorry, but for real?

I have friends named Alex, are they not allowed to name their own projects after themselves now?

Please stop this insanity.

**Comment by CodeForAllkind** [comment]
How dare you call me a troll? This is a very serious issue and should be discussed seriously.  This repo conflics with the Github Code of Conduct (which I will not reduce to CoC as that may have inappropriate connotations.)

**Comment by GreenTurtleOne** [comment]
How dare I criticize you for trolling? Okay.

**Comment by wooorm** [comment]
Interesting, especially that that form, `alexander`, comes from the more generic αλεξω (alexo, meaning `defending`). Let’s just say `alex` is derived from the latter, okay?

Happy Holidays! :christmas_tree:
