### ISSUE TITLE
Spastic / spaz alternatives, and more slang to be added

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [wooorm/alex#71]
So, `spaz` has been a huge part of my vocabulary for a rather long time; having recently been informed it's hurtful, I turned to `echo | alex` to see what alternatives might be found. I was surprised to see that `alex` assumes the word is being used in its' directly-offensive form (`may be insensitive, use \`person with cerebral palsy\` instead`), instead of as a slang for a hyperactive, or clumsy, or silly person, as it was used where I grew up.

Perhaps some alternatives for that usage could be hunted down and provided as well? (See [this really interesting writeup][1] on the linguistic development of this slang in the U.S. vs. the U.K., as an aside.)

(On the same note, `mental` and `scope` might need to be added as aliases to this.)

   [1]: <http://itre.cis.upenn.edu/~myl/languagelog/archives/003020.html>

**Comment by wooorm** [comment]
Good suggestion!
