### ISSUE TITLE
Splitting up output into ‘senses’, like a dictionary entry

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [wooorm/alex#72]
Writing up #71, I came across this:

```
> echo 'crazy' | alex
    1:1-1:6  warning  `crazy` may be insensitive, use `rude`, `mean`,
    `disgusting`, `vile`, `person with symptoms of mental illness`,
    `person with mental illness`, `person with symptoms of a mental
    disorder`, `person with a mental disorder` instead
```

So, there's obviously two different uses of `crazy` that this is trying to debug: basically-casual-slur, and actual-reference-to-ill-person. Even _lumping together_ these possibilities is … mildly hurtful; and in cases like this, I suspect it'd also be helpful to make it clear to those not already in the know, that saying “He was acting like a person with mental illness!” is not magically less-offensive than “He was acting crazy!”; suggesting all of those replacements wholesale is … less than ideal, I think?

If I'm not the only one that feels that way, here's my thought: it'd be helpful if replacements could be broken down into sections or ‘senses’, each with a short descriptive phrase of what the usage that might be replaced with one of <that category> of replacements:

```
> echo 'crazy' | alex
    1:1-1:6  warning  `crazy` may be insensitive. in context: referring
    to a difficult person or their unusual actions, use [`rude`, `mean`,
    `disgusting`, or `vile`] instead; in context: referring to a person
    afflicted by an actual illness, use [`person with symptoms of mental
    illness`, `person with mental illness`, `person with symptoms of a
    mental disorder`, or `person with a mental disorder`] instead
```

(That output could probably be further prettified, but I was assuming you'd want to keep each warning on a single line?)

Thoughts?

**Comment by wooorm** [comment]
Definitely like this idea! Thanks for taking the time to write this down :+1:

**Comment by wooorm** [comment]
Unfortunately, this will have to wait a bit. It will take quite some time to rewrite all messages, and I’d rather ship 2.0.0 now!

**Comment by ELLIOTTCABLE** [comment]
Doesn't bother me! (=

**Comment by wooorm** [comment]
:+1:

**Comment by lightyrs** [comment]
This is crucial.

**Comment by wooorm** [comment]
Closing for now, I’m still super open to it, but I don’t have time for it (apparently) on my own backlog. If anyone wants to work on this: ping me!

**Comment by ELLIOTTCABLE** [comment]
Is there a particular reason to leave this closed, despite it being an outstanding issue? It's totally okay to not have time to work on something — but I'd consider this a rather major problem with Alex, as it stands; and having an Issue like this standing out on the Issues page is the most effective way I can think of for an unmaintained project to encourage visitors to possibly contribute!

(Hope the feedback isn't unwelcome; I just *really* can't understand the current race-to-zero-open-issues, even-on-unmaintained/side-projects, culture.)
