### ISSUE TITLE
alex 2.0.0 has some trouble with `'`?

### ISSUE THREAD

**Issue by kvz** [wooorm/alex#73]
I think this screen will illustrate best

![](https://dl.dropboxusercontent.com/s/anq9iiz9m2un067/2016-02-04%20at%2011.18.png?dl=0)

**Comment by wooorm** [comment]
Thanks, I’ll dig in!

**Comment by wooorm** [comment]
Okay, the three commits above fix the warnings you mentioned. If you `rm -rf node_modules/` and `npm install` again, things should be operating normally!

Thanks again for raising the issue!

**Comment by kvz** [comment]
:100:
