### ISSUE TITLE
Hijacking is profane?

### ISSUE THREAD

**Issue by rugk** [wooorm/alex#75]
Hijacking is considered profane by Alex. However...
1) there is no alternative given
2) this word is often used in a technical context, where it is certainly not profane. See e.g. https://en.wikipedia.org/wiki/Browser_hijacking - there is no alternative term for that.

**Comment by wooorm** [comment]
@rugk Thanks for the suggestion, if you want this now you should add it to [`wooorm/profanities`](https://github.com/wooorm/profanities). [This file](https://github.com/wooorm/profanities/blob/master/script/not-so-bad.txt), to be exact.

**Comment by rugk** [comment]
Okay, [done](https://github.com/wooorm/profanities/pull/2). BTW "hijack" was already included.

**Comment by wooorm** [comment]
Whoops, forgot to close here. If you re-install alex your fix is included!
