### ISSUE TITLE
Profanity and equality “circles” / “dead-ends”

### ISSUE THREAD

**Issue by rmmonster** [wooorm/alex#78]
When I type "homosexual" in the demo alex states:

> homosexual may be insensitive, use gay, gay man, lesbian, gay person/people instead

When I type "gay" int the demo alex states:

> Don’t use “gay”, it’s profane

When I type "gay person" alex states:

> Don’t use “gay”, it’s profane

I don't know what term might seem appropriate in this case, but I think it should not promote the usage of words, which itself identifies as profane.

The easiest way out might be to change the warnings about profanities to something less absolute, like
> "gay" may be considered profane

**Comment by wooorm** [comment]
Thanks for suggesting, @rmmonster.

The profanities were recently added and this is a bug there.

**Comment by wooorm** [comment]
I added more nuance to the profanities. As both `homosexual` and `gay` can be used as profanities, both get messages (`Reconsider using “Homosexual”, it may be profane`, and `Be careful with “Gay”, it’s profane in some cases`). The retext-equality dependency also warns for `homosexual` (suggesting `gay` instead).

See [ignoring messages](https://github.com/wooorm/alex#ignoring-messages) to deal with unwanted messages in general.
