### ISSUE TITLE
Reverse mode

### ISSUE THREAD

**Issue by XstreamGit** [wooorm/alex#79]
I would like to suggest a reverse mode to make this project even more useful.  

With reverse mode for example instead of suggesting:
> "he" may be insensitive, use "they", "it" instead  

The tool would suggest:
> "they" may be imprecise, use "he", "she" instead

This would probably be easy to implement as it requires little more than swapping the words.

**Comment by wooorm** [comment]
That’s not going into alex and I’m not interested in working on it.

Luckily, someone on 4chan already did, I seem to remember it being called “XenaJS” but I’m not sure if it’s still online.
