### ISSUE TITLE
Suggestion: add "jew" / "jewed" as potential profanity

### ISSUE THREAD

**Issue by apapadimoulis** [wooorm/alex#80]
TRIGGER WARNING: profane and derogatory words are ahead

I see that both "gyp" and "gypsy" are considered profane, as they are derogatory to Romani people. 

However, as a Jew, I find it troubling that alexjs does not see a problem "jew" and "jewed". For example, "I overpaid by $20, he guy totally jewed me." Or, "that guy is such a jew."

In this case, the replacement suggests should be "that individual totally `ripped me off`" and "that individual is such a `frugal-minded person`"

**Comment by wooorm** [comment]
I don’t like to add “jew”, as that’s a perfectly valid word, and from my reading it is the preferred term for that group. Unlike “gyp”, which is not the preferred term by a group of people. If you don’t agree, please supply a source.

Regarding “jewed”, I agree, please provide a source.

Also, I suggest request a pull on [retext-equality](https://github.com/wooorm/retext-equality) if you want to move this along.

From your profile and your tweet, you don’t seem to have much experience with open source. Please let me know if I can help and advice with that.

**Comment by polygeekery** [comment]
> I don’t like to add “jew”, as that’s a perfectly valid word

Then what justification do you have for including the following words?

- headlights
- tinkle
- urine
- urinate
- kumquat
- niggle
- niggled
- niggles
- niggardly
- lactate
- nuke
- propoganda
- radical
- nymph
- primetime
- rigger
- roach
- robber
- satan
- screw
- septic
- shinola
- shooting
- sick
- slant
- slope
- smack
- snigger
- tar baby

??

This is only a small selection of the words in your json file that are not profane.  I mean...I guess a few of them *could* be in very specific context.  But by adding all of these silly words you only make your software completely useless due to all of the false positives it will flag.

**Comment by boomzillawtf** [comment]
Bah. That sounds like jew talk.

**Comment by apapadimoulis** [comment]
I may not be a big open source contributor, but I am a staunch believer in inclusiveness and I think we, as an industry, need to be focusing more energy on helping people avoid microagressions. This project is a good step in that direction, and this was one way I thought I contribute (the website suggested to post a note here).

As a member of "that group", I can say that "jew" (note the casing) is most certainly not a valid word, and is *far more* offensive than "gyp". Culturally speaking, Romani people are generally nomads and thieves, and they even themselves use the word "gyp" when describing their ways.

I grew up around a Romani family, and they joked about gyping people all the time. Watch the show Gypsy Wedding, and they use it constantly.

**However** as a Jew (note the capitalization, because it's a proper noun) / Jewish person (again, capitalization), it's true that we are culturally frugal people, but we most certainly do *not* use the word "jew" when describing our ways.

So, yes, it's highly offensive to all Jews that you would consider "gyp" and "gypsie" profane (even when Romani people do not), but are perfectly acceptable with "jew" and "jewed".

**Comment by apapadimoulis** [comment]
@boomzillawtf, while I'm certain your intention was not to offend, but instead to illustrate how "jew" can be used in an offensive manner... as a Jew, I would appreciate if you are more considerate when illustrating offensive uses of language surrounding the **completely invalid word** "jew"

**Comment by boomzillawtf** [comment]
Bah. That sounds like Jew talk.

**Comment by DogsB** [comment]
@boomzillawtf that is a horrendious insult. How can you be so trangressive against your fellow human beans. The **J**ew**ish** people are a proud and noble race whose lack of privilegde has caused them great hardship over the millenia. They are a strong people deserving of your respect.

**Comment by cartmanwtf** [comment]
Oh, nice Kyle. So you're now impersonating this @apapadimoulis guy?!

I knew it! I knew it the moment you bought your first Internet-enabled computer that you'd simply go out there and grab the first chance to jew us all over. First you kill our savior Jesus Christ and now this! You jews just don't know where to stop!

Don't think I'll let you win you back-stabbing piece of shit! I'm gonna get you. I'm gonna get you! I'm gonna get you, bro!

**Comment by wooorm** [comment]
@apapadimoulis Your words have convinced me, but your tweet makes me doubt intent. Please provide a source.

Also: if a group refers to themselves in a certain way, think of Hip Hop culture, doesn’t make those references OK in general.
And, importantly, this is not a race between whichever group is most offended by a given reference.

**Comment by apapadimoulis** [comment]
@wooorm the fact that you want a source for the inappropriateness of "jew" yet classify the long list of words that @polygeekery mentioned as profane makes me doubt this project's sincerity and your intent.

Jew is a proper noun. The spellchecker puts a red squiggly line under "jew" and suggests Jew as the correction. For a source, just look in literally any English dictionary ever written. 

The word "hip hop" however, is *not* considered a proper noun (source: literally every single English dictionary ever written), yet you chose to capitalize it? This is why I question the sincerity here -- and frankly I'm finding it really hard to see this attitude as anything but anti-Semitic. 

So, it's seems were at a bit of a Mexican standoff[1]. Neither of us can tell whether the other one is sincere or not. But, for either the sake of helping people avoid microagressions, or for continuing the parody of said objective, "jew" most certainly should be considered profane.

[1] again note the capitalization of a proper noun; also, as far as I'm aware, that word is not considered insensitive and is not etymologically racist; however I do apologize in if anyone was offended by my usage

**Comment by polygeekery** [comment]
@wooorm, would you be interested in a pull request that removes all of the words that are not profanity?  If your project is serious, and I am beginning to doubt it is much the same as @apapadimoulis is, you would want to remove the words that are not profane or that would likely trigger more false positives than do real good.

**Comment by wooorm** [comment]
Hey @polygeekery, @apapadimoulis, your trolling was fun but now you’re boring me.

@polygeekery Yeah, sure, I suggest removing them from [`wooorm/profanities`](https://github.com/wooorm/profanities), through the [`not-so-bad.txt`](https://github.com/wooorm/profanities/blob/master/script/not-so-bad.txt) file. I suggest only removing the really-not-that-offensive words (e.g., `nuke`).

**Comment by whelaro** [comment]
@wooorm I don't think @apapadimoulis is trying to troll you. As for sources, I've heard it used in the negative ways that @apapadimoulis has described, but from Urban Dictionary as a quick source for this sort of thing:

jewed - verb. To get screwed over or cheated out of something.
jew - Derogatory term for someone tight with their money or someone not very generous.

the 20 words related to jew section (on mobile, at least) include a lot of other slurs that would fall into this category as well.

**Comment by wooorm** [comment]
The message for `Jew` is now `Be careful with “Jew”, it’s profane in some cases`; and for `Jewed`, `Don’t use “Jewed”, it’s profane`; which I believe covers several uses of the phrases correctly.
