### ISSUE TITLE
Suggestion: “Niggardly” should be categorised as “often mistaken as profanity” not “profanity”

### ISSUE THREAD

**Issue by apapadimoulis** [wooorm/alex#81]
TRIGGER WARNING: words that are often mistaken as profanity ahead, as well as references to profane words

Currently, alexjs considers "niggardly" to be "profane".

Although niggardly should always be avoided due to its homophonous relationship to that disgustingly offensive “n-word”, my concern is that a writer with a profound vocabulary who's looking to find the perfect balance between “miserly” and “Scrooge-esque” would take offense to his writing being classified as "profane".

Please change the category to "often mistaken as profanity".

**Comment by wooorm** [comment]
Thanks for the suggestion, @apapadimoulis. In the future I’d like to make this kind of grading possible though!

**Comment by wooorm** [comment]
The message for `Niggardly` is now `Be careful with “Niggardly”, it’s profane in some cases`, which I believe covers several uses of the phrase correctly.
