### ISSUE TITLE
Rename "master" branch to "primary"

### ISSUE THREAD

**Issue by Starefossen** [wooorm/alex#84]
Keeping within the spirit of Alex's rule set; the `master` git branch for this repository should be renamed to `primary`.

**Comment by wooorm** [comment]
😂

**Comment by Hypnosphi** [comment]
FYI: this is actually possible, see [my fork](https://github.com/Hypnosphi/alex)

You need to create and push `primary` branch, then go to [Branches settings](https://github.com/get-alex/alex/settings/branches) and set it as default branch. After that, you'll be  able to remove the M-word branch completly on [Branches tab](https://github.com/get-alex/alex/branches)

**Comment by paulmwatson** [comment]
@Starefossen ahead of their time. In 2020 now and `main` might be a good alternative.

**Comment by wooorm** [comment]
Yes! Wholeheartedly agree!

The time this was posted, was a time when we got tons of troll issues, and the lack of argumentation did not take that doubt away. Back then, the master branch was not seen as inconsiderate by many. Language changes, which is good, so yes we should do it!

I today heard that gh was working on tooling to make this easier: https://twitter.com/techpickles/status/1271274321172979717

**Comment by dcorb** [comment]
I'm glad to see your reaction @wooorm 🙌  
At first, I thought it's a reference to "master" copy but actually this thread explains quite well that it's a reference to master/slave https://twitter.com/mislav/status/1270388510684598272

**Comment by Starefossen** [comment]
Just for the reference; this was never meant as a troll issue, but I can understand why it could have been interpreted that way with lack of context ❤️

**Comment by wooorm** [comment]
Done, it’s `main` now!
