### ISSUE TITLE
Suggestion: `spa`

### ISSUE THREAD

**Issue by iandioch** [wooorm/alex#89]
Where I am, `spa` is used instead of `spaz`. I saw it come up in a document today (that I plan on running through Alex, however the program will miss this regional slang). Going by a [few](http://www.urbandictionary.com/define.php?term=spa&defid=3589483) relevant [mentions](http://www.urbandictionary.com/define.php?term=spa&defid=713178) on Urban Dictionary, this only happens in Ireland, but it is pretty much the only form of the word used here, and is very offensive.

This might be related to #71, and #72.

**Comment by wooorm** [comment]
Great idea, thanks for suggesting! There’s quite some chance of false positives though, so I’ll need to think about how to implement it.

**Comment by wooorm** [comment]
The message for `Spa` is now `Be careful with “Spa”, it’s profane in some cases`, which I believe covers several uses of the phrase correctly.
