### ISSUE TITLE
Suggestion: `shemale` and `he-she`

### ISSUE THREAD

**Issue by JayYang95** [wooorm/alex#91]
I noticed that alex has covered some offensive terms such as "tranny" but has failed to include some equally offensive ones such as these.

Input:
echo "That person is a he-she." | alex

returns no issues found

Input:
echo "That person is a shemale." | alex

also returns no issues found

**Comment by yoshuawuyts** [comment]
Oh yeah, those should def be included. PR welcome!

**Comment by eah13** [comment]
@yoshuawuyts would the correct place to fix this be here? https://github.com/wooorm/retext-equality/blob/master/lib/patterns.json#L4542

**Comment by yoshuawuyts** [comment]
@eah13 Yeah, that seems about right :sparkles:

**Comment by wooorm** [comment]
Close! The `patterns.json` file is created from the YAML databases in [`script/`](https://github.com/wooorm/retext-equality/tree/master/script). I’d appreciate it if you add it there.

P.S. I’ll add a section in the README about contributing 👍

**Comment by wooorm** [comment]
Added the [section on `wooorm/retext-equality`](https://github.com/wooorm/retext-equality#contributing). Also: what do you suggest instead?

P.S. Great suggestion! 🎉
