### ISSUE TITLE
Suggestion: `Chinese` isn’t profane.

### ISSUE THREAD

**Issue by HopefulLlama** [wooorm/alex#92]
alex flags any usage of the word "Chinese" as profane. 

I don't think it is, but there is always the chance that I'm wrong.
If it isn't, it is probably best to remove "Chinese" from the profanity list.

**Comment by wooorm** [comment]
Agreed! 👍

I recently included a list of profane words and it’s overly sensitive. I’m currently in the process of rating how big the chance is that those words are or aren’t profane, and adjust messages accordingly.

It’s a lot of work so it will take a while though, thanks for your patience :)

**Comment by HopefulLlama** [comment]
Fair! Is there any way I can help?

**Comment by wooorm** [comment]
Seems I just lost the work ’till now, but the project is here: <https://github.com/wooorm/cuss>. If you’re interested in helping, fork it, and rate the phrases in `data/index.json` (`0`, `1`, or `2`). See the readme for more info and examples! :)

**Comment by wooorm** [comment]
The message for `Chinese` is now `Be careful with “Chinese”, it’s profane in some cases`, which I believe covers several uses of the phrase correctly.
