### ISSUE TITLE
Readme is confusing

### ISSUE THREAD

**Issue by ms-217** [wooorm/alex#94]
There are some grammar and clarity issues with the README.md. Some of the lines I found very confusing. For example:

> **alex** is also as an AMD, CommonJS, and globals module, uncompressed and compressed

I think you should add "available" to this line. It looks like you missed it completely.

I say we should take some time and proofread our files a bit.

**Comment by wooorm** [comment]
> I say we should take some time and proofread our files a bit.

I say we shouldn’t be passive aggressive.

**Comment by ms-217** [comment]
> > I say we should take some time and proofread our files a bit.

> I say we shouldn’t be passive aggressive.

I'll take that into consideration next time. :angry: :arrow_backward: grrr aggressive

**Comment by wooorm** [comment]
Haha, great!

Thanks for the suggestions!
