### ISSUE TITLE
Add option `--quiet`

### ISSUE THREAD

**Issue by evilebottnawi** [wooorm/alex#99]
For output only errors.

**Comment by wooorm** [comment]
Could you expand on that?

**Comment by evilebottnawi** [comment]
@wooorm not output
```shell
README.md: no issues found
LICENSE.md: no issues found
```
Only if error exist.

**Comment by RRorg** [comment]
I think the OP meant to type `--quiet`, which will suppress all output unless an error is encountered, useful for e.g. piping commands.

**Comment by evilebottnawi** [comment]
@RRorg yes

**Comment by evilebottnawi** [comment]
@wooorm Thanks!
